all: 
	g++ main.cpp ../taint_method/helper.cpp -L../taint_method -lTaintGenLib

debug:
	g++ -g main.cpp ../taint_method/helper.cpp -L../taint_method -lTaintGenLib

dla:
	./a.out /workspace/research/ILA/autoGenILA/NVDLA/SYN/file_list.txt /workspace/research/ILA/autoGenILA/NVDLA/SYN
