clang ila.c -emit-llvm -S -o main.ll

llvm-link -v main.ll \
lui_\fifo_addr.r0_7.ll \
auipc_\fifo_addr.r0_7.ll \
addi_\fifo_addr.r0_8.ll \
slti_\fifo_addr.r0_8.ll \
sltiu_\fifo_addr.r0_8.ll \
xori_\fifo_addr.r0_8.ll \
ori_\fifo_addr.r0_8.ll \
andi_\fifo_addr.r0_8.ll \
add_\fifo_addr.r0_8.ll \
sub_\fifo_addr.r0_8.ll \
sll_\fifo_addr.r0_8.ll \
slt_\fifo_addr.r0_8.ll \
sltu_\fifo_addr.r0_8.ll \
xor_\fifo_addr.r0_8.ll \
srl_\fifo_addr.r0_8.ll \
sra_\fifo_addr.r0_8.ll \
or_\fifo_addr.r0_8.ll \
and_\fifo_addr.r0_8.ll \
jal_\fifo_addr.r0_5.ll \
jalr_\fifo_addr.r0_6.ll \
lui_\fifo_instr.r0_7.ll \
auipc_\fifo_instr.r0_7.ll \
addi_\fifo_instr.r0_8.ll \
slti_\fifo_instr.r0_8.ll \
sltiu_\fifo_instr.r0_8.ll \
xori_\fifo_instr.r0_8.ll \
ori_\fifo_instr.r0_8.ll \
andi_\fifo_instr.r0_8.ll \
add_\fifo_instr.r0_8.ll \
sub_\fifo_instr.r0_8.ll \
sll_\fifo_instr.r0_8.ll \
slt_\fifo_instr.r0_8.ll \
sltu_\fifo_instr.r0_8.ll \
xor_\fifo_instr.r0_8.ll \
srl_\fifo_instr.r0_8.ll \
sra_\fifo_instr.r0_8.ll \
or_\fifo_instr.r0_8.ll \
and_\fifo_instr.r0_8.ll \
jal_\fifo_instr.r0_5.ll \
jalr_\fifo_instr.r0_6.ll \
lui_\fifo_valid.r0_7.ll \
auipc_\fifo_valid.r0_7.ll \
addi_\fifo_valid.r0_8.ll \
slti_\fifo_valid.r0_8.ll \
sltiu_\fifo_valid.r0_8.ll \
xori_\fifo_valid.r0_8.ll \
ori_\fifo_valid.r0_8.ll \
andi_\fifo_valid.r0_8.ll \
add_\fifo_valid.r0_8.ll \
sub_\fifo_valid.r0_8.ll \
sll_\fifo_valid.r0_8.ll \
slt_\fifo_valid.r0_8.ll \
sltu_\fifo_valid.r0_8.ll \
xor_\fifo_valid.r0_8.ll \
srl_\fifo_valid.r0_8.ll \
sra_\fifo_valid.r0_8.ll \
or_\fifo_valid.r0_8.ll \
and_\fifo_valid.r0_8.ll \
jal_\fifo_valid.r0_5.ll \
jalr_\fifo_valid.r0_6.ll \
lui_\fifo_wstrb.r0_7.ll \
auipc_\fifo_wstrb.r0_7.ll \
addi_\fifo_wstrb.r0_8.ll \
slti_\fifo_wstrb.r0_8.ll \
sltiu_\fifo_wstrb.r0_8.ll \
xori_\fifo_wstrb.r0_8.ll \
ori_\fifo_wstrb.r0_8.ll \
andi_\fifo_wstrb.r0_8.ll \
add_\fifo_wstrb.r0_8.ll \
sub_\fifo_wstrb.r0_8.ll \
sll_\fifo_wstrb.r0_8.ll \
slt_\fifo_wstrb.r0_8.ll \
sltu_\fifo_wstrb.r0_8.ll \
xor_\fifo_wstrb.r0_8.ll \
srl_\fifo_wstrb.r0_8.ll \
sra_\fifo_wstrb.r0_8.ll \
or_\fifo_wstrb.r0_8.ll \
and_\fifo_wstrb.r0_8.ll \
jal_\fifo_wstrb.r0_5.ll \
jalr_\fifo_wstrb.r0_6.ll \
lui_\u0.mem_addr_7.ll \
auipc_\u0.mem_addr_7.ll \
addi_\u0.mem_addr_8.ll \
slti_\u0.mem_addr_8.ll \
sltiu_\u0.mem_addr_8.ll \
xori_\u0.mem_addr_8.ll \
ori_\u0.mem_addr_8.ll \
andi_\u0.mem_addr_8.ll \
add_\u0.mem_addr_8.ll \
sub_\u0.mem_addr_8.ll \
sll_\u0.mem_addr_8.ll \
slt_\u0.mem_addr_8.ll \
sltu_\u0.mem_addr_8.ll \
xor_\u0.mem_addr_8.ll \
srl_\u0.mem_addr_8.ll \
sra_\u0.mem_addr_8.ll \
or_\u0.mem_addr_8.ll \
and_\u0.mem_addr_8.ll \
jal_\u0.mem_addr_5.ll \
jalr_\u0.mem_addr_6.ll \
sw_\u0.mem_addr_8.ll \
sb_\u0.mem_addr_8.ll \
sh_\u0.mem_addr_8.ll \
lui_\u0.cpuregs[1]_7.ll \
auipc_\u0.cpuregs[1]_7.ll \
addi_\u0.cpuregs[1]_8.ll \
slti_\u0.cpuregs[1]_8.ll \
sltiu_\u0.cpuregs[1]_8.ll \
xori_\u0.cpuregs[1]_8.ll \
ori_\u0.cpuregs[1]_8.ll \
andi_\u0.cpuregs[1]_8.ll \
add_\u0.cpuregs[1]_8.ll \
sub_\u0.cpuregs[1]_8.ll \
sll_\u0.cpuregs[1]_8.ll \
slt_\u0.cpuregs[1]_8.ll \
sltu_\u0.cpuregs[1]_8.ll \
xor_\u0.cpuregs[1]_8.ll \
srl_\u0.cpuregs[1]_8.ll \
sra_\u0.cpuregs[1]_8.ll \
or_\u0.cpuregs[1]_8.ll \
and_\u0.cpuregs[1]_8.ll \
jal_\u0.cpuregs[1]_5.ll \
addi_\u0.cpuregs[2]_8.ll \
slti_\u0.cpuregs[2]_8.ll \
sltiu_\u0.cpuregs[2]_8.ll \
xori_\u0.cpuregs[2]_8.ll \
ori_\u0.cpuregs[2]_8.ll \
andi_\u0.cpuregs[2]_8.ll \
add_\u0.cpuregs[2]_8.ll \
sub_\u0.cpuregs[2]_8.ll \
sll_\u0.cpuregs[2]_8.ll \
slt_\u0.cpuregs[2]_8.ll \
sltu_\u0.cpuregs[2]_8.ll \
xor_\u0.cpuregs[2]_8.ll \
srl_\u0.cpuregs[2]_8.ll \
sra_\u0.cpuregs[2]_8.ll \
or_\u0.cpuregs[2]_8.ll \
and_\u0.cpuregs[2]_8.ll \
jal_\u0.cpuregs[2]_5.ll \
addi_\u0.cpuregs[31]_8.ll \
slti_\u0.cpuregs[31]_8.ll \
sltiu_\u0.cpuregs[31]_8.ll \
xori_\u0.cpuregs[31]_8.ll \
ori_\u0.cpuregs[31]_8.ll \
andi_\u0.cpuregs[31]_8.ll \
add_\u0.cpuregs[31]_8.ll \
sub_\u0.cpuregs[31]_8.ll \
sll_\u0.cpuregs[31]_8.ll \
slt_\u0.cpuregs[31]_8.ll \
sltu_\u0.cpuregs[31]_8.ll \
xor_\u0.cpuregs[31]_8.ll \
srl_\u0.cpuregs[31]_8.ll \
sra_\u0.cpuregs[31]_8.ll \
or_\u0.cpuregs[31]_8.ll \
and_\u0.cpuregs[31]_8.ll \
jal_\u0.cpuregs[31]_5.ll \
lui_\u0.mem_instr_7.ll \
auipc_\u0.mem_instr_7.ll \
addi_\u0.mem_instr_8.ll \
slti_\u0.mem_instr_8.ll \
sltiu_\u0.mem_instr_8.ll \
xori_\u0.mem_instr_8.ll \
ori_\u0.mem_instr_8.ll \
andi_\u0.mem_instr_8.ll \
add_\u0.mem_instr_8.ll \
sub_\u0.mem_instr_8.ll \
sll_\u0.mem_instr_8.ll \
slt_\u0.mem_instr_8.ll \
sltu_\u0.mem_instr_8.ll \
xor_\u0.mem_instr_8.ll \
srl_\u0.mem_instr_8.ll \
sra_\u0.mem_instr_8.ll \
or_\u0.mem_instr_8.ll \
and_\u0.mem_instr_8.ll \
jal_\u0.mem_instr_5.ll \
jalr_\u0.mem_instr_6.ll \
beq_\u0.mem_instr_8.ll \
bne_\u0.mem_instr_8.ll \
blt_\u0.mem_instr_8.ll \
bge_\u0.mem_instr_8.ll \
bltu_\u0.mem_instr_8.ll \
bgeu_\u0.mem_instr_8.ll \
sw_\u0.mem_instr_8.ll \
sb_\u0.mem_instr_8.ll \
sh_\u0.mem_instr_8.ll \
lui_\u0.mem_valid_7.ll \
auipc_\u0.mem_valid_7.ll \
addi_\u0.mem_valid_8.ll \
slti_\u0.mem_valid_8.ll \
sltiu_\u0.mem_valid_8.ll \
xori_\u0.mem_valid_8.ll \
ori_\u0.mem_valid_8.ll \
andi_\u0.mem_valid_8.ll \
add_\u0.mem_valid_8.ll \
sub_\u0.mem_valid_8.ll \
sll_\u0.mem_valid_8.ll \
slt_\u0.mem_valid_8.ll \
sltu_\u0.mem_valid_8.ll \
xor_\u0.mem_valid_8.ll \
srl_\u0.mem_valid_8.ll \
sra_\u0.mem_valid_8.ll \
or_\u0.mem_valid_8.ll \
and_\u0.mem_valid_8.ll \
jal_\u0.mem_valid_5.ll \
jalr_\u0.mem_valid_6.ll \
beq_\u0.mem_valid_8.ll \
bne_\u0.mem_valid_8.ll \
blt_\u0.mem_valid_8.ll \
bge_\u0.mem_valid_8.ll \
bltu_\u0.mem_valid_8.ll \
bgeu_\u0.mem_valid_8.ll \
sw_\u0.mem_valid_8.ll \
sb_\u0.mem_valid_8.ll \
sh_\u0.mem_valid_8.ll \
sw_\u0.mem_wdata_8.ll \
sb_\u0.mem_wdata_8.ll \
sh_\u0.mem_wdata_8.ll \
lui_\u0.mem_wstrb_7.ll \
auipc_\u0.mem_wstrb_7.ll \
addi_\u0.mem_wstrb_8.ll \
slti_\u0.mem_wstrb_8.ll \
sltiu_\u0.mem_wstrb_8.ll \
xori_\u0.mem_wstrb_8.ll \
ori_\u0.mem_wstrb_8.ll \
andi_\u0.mem_wstrb_8.ll \
add_\u0.mem_wstrb_8.ll \
sub_\u0.mem_wstrb_8.ll \
sll_\u0.mem_wstrb_8.ll \
slt_\u0.mem_wstrb_8.ll \
sltu_\u0.mem_wstrb_8.ll \
xor_\u0.mem_wstrb_8.ll \
srl_\u0.mem_wstrb_8.ll \
sra_\u0.mem_wstrb_8.ll \
or_\u0.mem_wstrb_8.ll \
and_\u0.mem_wstrb_8.ll \
jalr_\u0.mem_wstrb_6.ll \
beq_\u0.mem_wstrb_8.ll \
bne_\u0.mem_wstrb_8.ll \
blt_\u0.mem_wstrb_8.ll \
bge_\u0.mem_wstrb_8.ll \
bltu_\u0.mem_wstrb_8.ll \
bgeu_\u0.mem_wstrb_8.ll \
sw_\u0.mem_wstrb_8.ll \
sb_\u0.mem_wstrb_8.ll \
sh_\u0.mem_wstrb_8.ll \
lui_\u0.reg_next_pc_6.ll \
auipc_\u0.reg_next_pc_6.ll \
addi_\u0.reg_next_pc_6.ll \
slti_\u0.reg_next_pc_6.ll \
sltiu_\u0.reg_next_pc_6.ll \
xori_\u0.reg_next_pc_6.ll \
ori_\u0.reg_next_pc_6.ll \
andi_\u0.reg_next_pc_6.ll \
add_\u0.reg_next_pc_7.ll \
sub_\u0.reg_next_pc_7.ll \
sll_\u0.reg_next_pc_7.ll \
slt_\u0.reg_next_pc_7.ll \
sltu_\u0.reg_next_pc_7.ll \
xor_\u0.reg_next_pc_7.ll \
srl_\u0.reg_next_pc_7.ll \
sra_\u0.reg_next_pc_7.ll \
or_\u0.reg_next_pc_7.ll \
and_\u0.reg_next_pc_7.ll \
jal_\u0.reg_next_pc_5.ll \
jalr_\u0.reg_next_pc_6.ll \
beq_\u0.reg_next_pc_6.ll \
bne_\u0.reg_next_pc_6.ll \
blt_\u0.reg_next_pc_6.ll \
bge_\u0.reg_next_pc_6.ll \
bltu_\u0.reg_next_pc_6.ll \
bgeu_\u0.reg_next_pc_6.ll \
sw_\u0.reg_next_pc_8.ll \
sb_\u0.reg_next_pc_8.ll \
sh_\u0.reg_next_pc_8.ll \
lui_trap_7.ll \
auipc_trap_7.ll \
addi_trap_8.ll \
slti_trap_8.ll \
sltiu_trap_8.ll \
xori_trap_8.ll \
ori_trap_8.ll \
andi_trap_8.ll \
add_trap_8.ll \
sub_trap_8.ll \
sll_trap_8.ll \
slt_trap_8.ll \
sltu_trap_8.ll \
xor_trap_8.ll \
srl_trap_8.ll \
sra_trap_8.ll \
or_trap_8.ll \
and_trap_8.ll \
jalr_trap_6.ll \
beq_trap_8.ll \
bne_trap_8.ll \
blt_trap_8.ll \
bge_trap_8.ll \
bltu_trap_8.ll \
bgeu_trap_8.ll \
sw_\fifo_addr.r0_9.ll \
sb_\fifo_addr.r0_9.ll \
sh_\fifo_addr.r0_9.ll \
sw_\fifo_addr.r1_9.ll \
sb_\fifo_addr.r1_9.ll \
sh_\fifo_addr.r1_9.ll \
sw_\fifo_instr.r0_9.ll \
sb_\fifo_instr.r0_9.ll \
sh_\fifo_instr.r0_9.ll \
sw_\fifo_instr.r1_9.ll \
sb_\fifo_instr.r1_9.ll \
sh_\fifo_instr.r1_9.ll \
sw_\fifo_valid.r0_9.ll \
sb_\fifo_valid.r0_9.ll \
sh_\fifo_valid.r0_9.ll \
sw_\fifo_valid.r1_9.ll \
sb_\fifo_valid.r1_9.ll \
sh_\fifo_valid.r1_9.ll \
sw_\fifo_wdata.r0_9.ll \
sb_\fifo_wdata.r0_9.ll \
sh_\fifo_wdata.r0_9.ll \
sw_\fifo_wstrb.r0_9.ll \
sb_\fifo_wstrb.r0_9.ll \
sh_\fifo_wstrb.r0_9.ll \
sw_\fifo_wstrb.r1_9.ll \
sb_\fifo_wstrb.r1_9.ll \
sh_\fifo_wstrb.r1_9.ll \
beq_\fifo_addr.r0_9.ll \
bne_\fifo_addr.r0_9.ll \
blt_\fifo_addr.r0_9.ll \
bge_\fifo_addr.r0_9.ll \
bltu_\fifo_addr.r0_9.ll \
bgeu_\fifo_addr.r0_9.ll \
beq_\fifo_instr.r0_9.ll \
bne_\fifo_instr.r0_9.ll \
blt_\fifo_instr.r0_9.ll \
bge_\fifo_instr.r0_9.ll \
bltu_\fifo_instr.r0_9.ll \
bgeu_\fifo_instr.r0_9.ll \
beq_\fifo_valid.r0_9.ll \
bne_\fifo_valid.r0_9.ll \
blt_\fifo_valid.r0_9.ll \
bge_\fifo_valid.r0_9.ll \
bltu_\fifo_valid.r0_9.ll \
bgeu_\fifo_valid.r0_9.ll \
beq_\fifo_wstrb.r0_9.ll \
bne_\fifo_wstrb.r0_9.ll \
blt_\fifo_wstrb.r0_9.ll \
bge_\fifo_wstrb.r0_9.ll \
bltu_\fifo_wstrb.r0_9.ll \
bgeu_\fifo_wstrb.r0_9.ll \
sw_trap_9.ll \
sb_trap_9.ll \
sh_trap_9.ll \
-S -o linked.ll

clang linked.ll
clang ila.c -emit-llvm -S -o main.ll
llvm-link -v main.ll \
-S -o linked.ll
clang linked.ll
clang ila.c -emit-llvm -S -o main.ll
llvm-link -v main.ll \
beq_\u0.reg_next_pc_7.ll \
bne_\u0.reg_next_pc_7.ll \
blt_\u0.reg_next_pc_7.ll \
bge_\u0.reg_next_pc_7.ll \
bltu_\u0.reg_next_pc_7.ll \
bgeu_\u0.reg_next_pc_7.ll \
-S -o linked.ll
clang linked.ll
clang ila.c -emit-llvm -S -o main.ll
llvm-link -v main.ll \
beq_\u0.reg_next_pc_7.ll \
-S -o linked.ll
clang linked.ll
clang ila.c -emit-llvm -S -o main.ll
llvm-link -v main.ll \
beq_\u0.reg_next_pc_8.ll \
-S -o linked.ll
clang linked.ll
clang ila.c -emit-llvm -S -o main.ll
llvm-link -v main.ll \
-S -o linked.ll
clang linked.ll
clang ila.c -emit-llvm -S -o main.ll
llvm-link -v main.ll \
beq_\u0.reg_next_pc_8.ll \
-S -o linked.ll
clang linked.ll
clang ila.c -emit-llvm -S -o main.ll
llvm-link -v main.ll \
beq_\fifo_pc.r0_9.ll \
beq_\fifo_pc.r1_9.ll \
-S -o linked.ll
clang linked.ll
clang ila.c -emit-llvm -S -o main.ll
llvm-link -v main.ll \
beq_\fifo_pc.r0_9.ll \
beq_\fifo_pc.r1_9.ll \
-S -o linked.ll
clang linked.ll
clang ila.c -emit-llvm -S -o main.ll
llvm-link -v main.ll \
bne_\fifo_pc.r0_9.ll \
blt_\fifo_pc.r0_9.ll \
bge_\fifo_pc.r0_9.ll \
bltu_\fifo_pc.r0_9.ll \
bgeu_\fifo_pc.r0_9.ll \
bne_\fifo_pc.r1_9.ll \
blt_\fifo_pc.r1_9.ll \
bge_\fifo_pc.r1_9.ll \
bltu_\fifo_pc.r1_9.ll \
bgeu_\fifo_pc.r1_9.ll \
-S -o linked.ll
clang linked.ll

clang ila.c -emit-llvm -S -o main.ll
llvm-link -v main.ll \
lw_\fifo_addr.r0_9.ll \
lb_\fifo_addr.r0_9.ll \
lh_\fifo_addr.r0_9.ll \
lbu_\fifo_addr.r0_9.ll \
lhu_\fifo_addr.r0_9.ll \
lw_\fifo_instr.r0_9.ll \
lb_\fifo_instr.r0_9.ll \
lh_\fifo_instr.r0_9.ll \
lbu_\fifo_instr.r0_9.ll \
lhu_\fifo_instr.r0_9.ll \
lw_\fifo_pc.r0_9.ll \
lb_\fifo_pc.r0_9.ll \
lh_\fifo_pc.r0_9.ll \
lbu_\fifo_pc.r0_9.ll \
lhu_\fifo_pc.r0_9.ll \
lw_\fifo_valid.r0_9.ll \
lb_\fifo_valid.r0_9.ll \
lh_\fifo_valid.r0_9.ll \
lbu_\fifo_valid.r0_9.ll \
lhu_\fifo_valid.r0_9.ll \
lw_\fifo_wstrb.r0_9.ll \
lb_\fifo_wstrb.r0_9.ll \
lh_\fifo_wstrb.r0_9.ll \
lbu_\fifo_wstrb.r0_9.ll \
lhu_\fifo_wstrb.r0_9.ll \
lw_\u0.cpuregs[1]_9.ll \
lb_\u0.cpuregs[1]_9.ll \
lh_\u0.cpuregs[1]_9.ll \
lbu_\u0.cpuregs[1]_9.ll \
lhu_\u0.cpuregs[1]_9.ll \
lw_\u0.cpuregs[2]_9.ll \
lb_\u0.cpuregs[2]_9.ll \
lh_\u0.cpuregs[2]_9.ll \
lbu_\u0.cpuregs[2]_9.ll \
lhu_\u0.cpuregs[2]_9.ll \
lw_\u0.cpuregs[31]_9.ll \
lb_\u0.cpuregs[31]_9.ll \
lh_\u0.cpuregs[31]_9.ll \
lbu_\u0.cpuregs[31]_9.ll \
lhu_\u0.cpuregs[31]_9.ll \
lw_\u0.reg_next_pc_9.ll \
lb_\u0.reg_next_pc_9.ll \
lh_\u0.reg_next_pc_9.ll \
lbu_\u0.reg_next_pc_9.ll \
lhu_\u0.reg_next_pc_9.ll \
lw_trap_9.ll \
lb_trap_9.ll \
lh_trap_9.ll \
lbu_trap_9.ll \
lhu_trap_9.ll \
-S -o linked.ll
clang linked.ll
clang ila.c -emit-llvm -S -o main.ll
llvm-link -v main.ll \
lw_\fifo_addr.r1_9.ll \
lb_\fifo_addr.r1_9.ll \
lh_\fifo_addr.r1_9.ll \
lbu_\fifo_addr.r1_9.ll \
lhu_\fifo_addr.r1_9.ll \
lw_\fifo_instr.r1_9.ll \
lb_\fifo_instr.r1_9.ll \
lh_\fifo_instr.r1_9.ll \
lbu_\fifo_instr.r1_9.ll \
lhu_\fifo_instr.r1_9.ll \
lw_\fifo_pc.r1_9.ll \
lb_\fifo_pc.r1_9.ll \
lh_\fifo_pc.r1_9.ll \
lbu_\fifo_pc.r1_9.ll \
lhu_\fifo_pc.r1_9.ll \
lw_\fifo_valid.r1_9.ll \
lb_\fifo_valid.r1_9.ll \
lh_\fifo_valid.r1_9.ll \
lbu_\fifo_valid.r1_9.ll \
lhu_\fifo_valid.r1_9.ll \
lw_\fifo_wstrb.r1_9.ll \
lb_\fifo_wstrb.r1_9.ll \
lh_\fifo_wstrb.r1_9.ll \
lbu_\fifo_wstrb.r1_9.ll \
lhu_\fifo_wstrb.r1_9.ll \
-S -o linked.ll
clang linked.ll
clang ila.c -emit-llvm -S -o main.ll
llvm-link -v main.ll \
-S -o linked.ll
clang linked.ll
