main: instr_parser_test.cpp instr_parser.cpp instr_parser.h
	g++ -std=c++11 -Wall -o instr_parser instr_parser_test.cpp instr_parser.cpp

run:
	./instr_parser /workspace/research/ILA/autoGenILA/yosysScript/smt-gen/simple/simple_instr.txt
