main: btor_parser_test.cpp
	g++-9 -std=c++11 -o btor_parser btor_parser_test.cpp

debug: btor_parser.cpp
	g++-9 -g -std=c++11 -o btor_parser btor_parser_test.cpp

run:
	./btor_parser /workspace/research/ILA/autoGenILA/yosysScript/smt-gen/simple/simple.btor
