all:
	g++ taint_gen.cpp

adder:
	./a.out /workspace/research/ILA/autoGenILA/naiveEg/word_adder/word_adder_yosys.v

naive:
	./a.out /workspace/research/ILA/autoGenILA/naiveEg/naive/naive_yosys.v

two:
	./a.out /workspace/research/ILA/autoGenILA/naiveEg/two_reg/two_reg_yosys.v
