/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 9.0.0 -fPIC -Os) */

module picorv32(clk, resetn, trap, mem_valid, mem_instr, mem_ready, mem_addr, mem_wdata, mem_wstrb, mem_rdata, mem_la_read, mem_la_write, mem_la_addr, mem_la_wdata, mem_la_wstrb, pcpi_valid, pcpi_insn, pcpi_rs1, pcpi_rs2, pcpi_wr, pcpi_rd, pcpi_wait, pcpi_ready, irq, eoi, trace_valid, trace_data);
  wire [31:0] _0000_;
  wire _0001_;
  wire [63:0] _0002_;
  wire [63:0] _0003_;
  wire [7:0] _0004_;
  wire [31:0] _0005_;
  wire [31:0] _0006_;
  wire [4:0] _0007_;
  wire [4:0] _0008_;
  wire [4:0] _0009_;
  wire _0010_;
  wire _0011_;
  wire [31:0] _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire [4:0] _0072_;
  wire _0073_;
  wire _0074_;
  wire [31:0] _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire [31:0] _0081_;
  wire [1:0] _0082_;
  wire _0083_;
  wire [31:0] _0084_;
  wire [1:0] _0085_;
  wire [3:0] _0086_;
  wire _0087_;
  wire [31:0] _0088_;
  wire [31:0] _0089_;
  wire [31:0] _0090_;
  wire [31:0] _0091_;
  wire [31:0] _0092_;
  wire [4:0] _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire [15:0] _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire [31:0] _0103_;
  wire [7:0] _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire [31:0] _0111_;
  wire [31:0] _0112_;
  wire [63:0] _0113_;
  wire [31:0] _0114_;
  wire [63:0] _0115_;
  wire [31:0] _0116_;
  wire [31:0] _0117_;
  wire [31:0] _0118_;
  wire [29:0] _0119_;
  wire [31:0] _0120_;
  wire [31:0] _0121_;
  wire [31:0] _0122_;
  wire [3:0] _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire [7:0] _0193_;
  wire [7:0] _0194_;
  wire [31:0] _0195_;
  wire [31:0] _0196_;
  wire [31:0] _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire [31:0] _0347_;
  wire [31:0] _0348_;
  wire [31:0] _0349_;
  wire [31:0] _0350_;
  wire [31:0] _0351_;
  wire [31:0] _0352_;
  wire [31:0] _0353_;
  wire [31:0] _0354_;
  wire [31:0] _0355_;
  wire [31:0] _0356_;
  wire [31:0] _0357_;
  wire [31:0] _0358_;
  wire [31:0] _0359_;
  wire [31:0] _0360_;
  wire [31:0] _0361_;
  wire [31:0] _0362_;
  wire [31:0] _0363_;
  wire [31:0] _0364_;
  wire [31:0] _0365_;
  wire [31:0] _0366_;
  wire [31:0] _0367_;
  wire [31:0] _0368_;
  wire [31:0] _0369_;
  wire [31:0] _0370_;
  wire [31:0] _0371_;
  wire [31:0] _0372_;
  wire [31:0] _0373_;
  wire [31:0] _0374_;
  wire [31:0] _0375_;
  wire [31:0] _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire [31:0] _0409_;
  wire [31:0] _0410_;
  wire [31:0] _0411_;
  wire [31:0] _0412_;
  wire [31:0] _0413_;
  wire [31:0] _0414_;
  wire [31:0] _0415_;
  wire [31:0] _0416_;
  wire [31:0] _0417_;
  wire [31:0] _0418_;
  wire [31:0] _0419_;
  wire [31:0] _0420_;
  wire [31:0] _0421_;
  wire [31:0] _0422_;
  wire [31:0] _0423_;
  wire [31:0] _0424_;
  wire [31:0] _0425_;
  wire [31:0] _0426_;
  wire [31:0] _0427_;
  wire [31:0] _0428_;
  wire [31:0] _0429_;
  wire [31:0] _0430_;
  wire [31:0] _0431_;
  wire [31:0] _0432_;
  wire [31:0] _0433_;
  wire [31:0] _0434_;
  wire [31:0] _0435_;
  wire [31:0] _0436_;
  wire [31:0] _0437_;
  wire [31:0] _0438_;
  wire [31:0] _0439_;
  wire [31:0] _0440_;
  wire [31:0] _0441_;
  wire _0442_;
  wire [31:0] _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire [31:0] _0457_;
  wire [31:0] _0458_;
  wire [4:0] _0459_;
  wire _0460_;
  wire [4:0] _0461_;
  wire [4:0] _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire [7:0] _0479_;
  wire [7:0] _0480_;
  wire [7:0] _0481_;
  wire [7:0] _0482_;
  wire [7:0] _0483_;
  wire [7:0] _0484_;
  wire _0485_;
  wire [7:0] _0486_;
  wire [7:0] _0487_;
  wire [7:0] _0488_;
  wire [7:0] _0489_;
  wire [7:0] _0490_;
  wire [7:0] _0491_;
  wire [7:0] _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire [1:0] _0506_;
  wire [1:0] _0507_;
  wire [1:0] _0508_;
  wire [1:0] _0509_;
  wire [1:0] _0510_;
  wire [1:0] _0511_;
  wire [1:0] _0512_;
  wire [31:0] _0513_;
  wire [31:0] _0514_;
  wire [31:0] _0515_;
  wire [31:0] _0516_;
  wire [31:0] _0517_;
  wire [31:0] _0518_;
  wire [31:0] _0519_;
  wire [31:0] _0520_;
  wire [31:0] _0521_;
  wire [31:0] _0522_;
  wire [31:0] _0523_;
  wire [31:0] _0524_;
  wire [31:0] _0525_;
  wire [31:0] _0526_;
  wire [31:0] _0527_;
  wire [31:0] _0528_;
  wire [63:0] _0529_;
  wire [63:0] _0530_;
  wire _0531_;
  wire _0532_;
  wire [31:0] _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire [1:0] _0558_;
  wire [1:0] _0559_;
  wire _0560_;
  wire [1:0] _0561_;
  wire _0562_;
  wire [1:0] _0563_;
  wire [1:0] _0564_;
  wire _0565_;
  wire [1:0] _0566_;
  wire [1:0] _0567_;
  wire [1:0] _0568_;
  wire [3:0] _0569_;
  wire [3:0] _0570_;
  wire [3:0] _0571_;
  wire [31:0] _0572_;
  wire [31:0] _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire [3:0] _0595_;
  wire [31:0] _0596_;
  wire [31:0] _0597_;
  wire _0598_;
  wire [31:0] _0599_;
  wire [31:0] _0600_;
  wire [31:0] _0601_;
  wire [31:0] _0602_;
  wire [3:0] _0603_;
  wire [31:0] _0604_;
  wire [31:0] alu_add_sub;
  wire alu_eq;
  wire alu_lts;
  wire alu_ltu;
  wire [31:0] alu_out;
  wire alu_out_0;
  reg [31:0] alu_out_q;
  wire [31:0] alu_shl;
  wire [31:0] alu_shr;
  input clk;
  reg compressed_instr;
  reg [63:0] count_cycle;
  reg [63:0] count_instr;
  reg [7:0] cpu_state;
  reg [31:0] \cpuregs[0] ;
  reg [31:0] \cpuregs[10] ;
  reg [31:0] \cpuregs[11] ;
  reg [31:0] \cpuregs[12] ;
  reg [31:0] \cpuregs[13] ;
  reg [31:0] \cpuregs[14] ;
  reg [31:0] \cpuregs[15] ;
  reg [31:0] \cpuregs[16] ;
  reg [31:0] \cpuregs[17] ;
  reg [31:0] \cpuregs[18] ;
  reg [31:0] \cpuregs[19] ;
  reg [31:0] \cpuregs[1] ;
  reg [31:0] \cpuregs[20] ;
  reg [31:0] \cpuregs[21] ;
  reg [31:0] \cpuregs[22] ;
  reg [31:0] \cpuregs[23] ;
  reg [31:0] \cpuregs[24] ;
  reg [31:0] \cpuregs[25] ;
  reg [31:0] \cpuregs[26] ;
  reg [31:0] \cpuregs[27] ;
  reg [31:0] \cpuregs[28] ;
  reg [31:0] \cpuregs[29] ;
  reg [31:0] \cpuregs[2] ;
  reg [31:0] \cpuregs[30] ;
  reg [31:0] \cpuregs[31] ;
  reg [31:0] \cpuregs[3] ;
  reg [31:0] \cpuregs[4] ;
  reg [31:0] \cpuregs[5] ;
  reg [31:0] \cpuregs[6] ;
  reg [31:0] \cpuregs[7] ;
  reg [31:0] \cpuregs[8] ;
  reg [31:0] \cpuregs[9] ;
  wire [31:0] cpuregs_rs1;
  wire [31:0] cpuregs_rs2;
  wire [31:0] cpuregs_wrdata;
  wire cpuregs_write;
  wire [31:0] dbg_mem_addr;
  wire dbg_mem_instr;
  wire [31:0] dbg_mem_rdata;
  wire dbg_mem_ready;
  wire dbg_mem_valid;
  wire [31:0] dbg_mem_wdata;
  wire [3:0] dbg_mem_wstrb;
  reg [31:0] decoded_imm;
  reg [31:0] decoded_imm_j;
  reg [4:0] decoded_rd;
  wire [4:0] decoded_rs;
  reg [4:0] decoded_rs1;
  reg [4:0] decoded_rs2;
  reg decoder_pseudo_trigger;
  reg decoder_pseudo_trigger_q;
  reg decoder_trigger;
  reg decoder_trigger_q;
  wire do_waitirq;
  output [31:0] eoi;
  reg [31:0] eoi;
  reg instr_add;
  reg instr_addi;
  reg instr_and;
  reg instr_andi;
  reg instr_auipc;
  reg instr_beq;
  reg instr_bge;
  reg instr_bgeu;
  reg instr_blt;
  reg instr_bltu;
  reg instr_bne;
  reg instr_ecall_ebreak;
  reg instr_jal;
  reg instr_jalr;
  reg instr_lb;
  reg instr_lbu;
  reg instr_lh;
  reg instr_lhu;
  reg instr_lui;
  reg instr_lw;
  reg instr_or;
  reg instr_ori;
  reg instr_rdcycle;
  reg instr_rdcycleh;
  reg instr_rdinstr;
  reg instr_rdinstrh;
  reg instr_retirq;
  reg instr_sb;
  reg instr_sh;
  reg instr_sll;
  reg instr_slli;
  reg instr_slt;
  reg instr_slti;
  reg instr_sltiu;
  reg instr_sltu;
  reg instr_sra;
  reg instr_srai;
  reg instr_srl;
  reg instr_srli;
  reg instr_sub;
  reg instr_xor;
  reg instr_xori;
  input [31:0] irq;
  reg is_alu_reg_imm;
  reg is_alu_reg_reg;
  reg is_beq_bne_blt_bge_bltu_bgeu;
  reg is_compare;
  reg is_jalr_addi_slti_sltiu_xori_ori_andi;
  reg is_lb_lh_lw_lbu_lhu;
  reg is_lbu_lhu_lw;
  reg is_lui_auipc_jal;
  reg is_lui_auipc_jal_jalr_addi_add_sub;
  wire is_rdcycle_rdcycleh_rdinstr_rdinstrh;
  reg is_sb_sh_sw;
  reg is_slli_srli_srai;
  reg is_slti_blt_slt;
  reg is_sltiu_bltu_sltu;
  reg latched_branch;
  reg latched_compr;
  reg latched_is_lh;
  reg latched_is_lu;
  reg [4:0] latched_rd;
  reg latched_stalu;
  reg latched_store;
  output [31:0] mem_addr;
  reg [31:0] mem_addr;
  reg mem_do_prefetch;
  reg mem_do_rdata;
  reg mem_do_rinst;
  reg mem_do_wdata;
  wire mem_done;
  output mem_instr;
  reg mem_instr;
  output [31:0] mem_la_addr;
  output mem_la_read;
  output [31:0] mem_la_wdata;
  output mem_la_write;
  output [3:0] mem_la_wstrb;
  input [31:0] mem_rdata;
  wire [31:0] mem_rdata_latched;
  wire [31:0] mem_rdata_latched_noshuffle;
  reg [31:0] mem_rdata_q;
  wire [31:0] mem_rdata_word;
  input mem_ready;
  reg [1:0] mem_state;
  output mem_valid;
  reg mem_valid;
  output [31:0] mem_wdata;
  reg [31:0] mem_wdata;
  reg [1:0] mem_wordsize;
  output [3:0] mem_wstrb;
  reg [3:0] mem_wstrb;
  wire mem_xfer;
  wire [31:0] next_pc;
  output [31:0] pcpi_insn;
  input [31:0] pcpi_rd;
  input pcpi_ready;
  output [31:0] pcpi_rs1;
  output [31:0] pcpi_rs2;
  output pcpi_valid;
  reg pcpi_valid;
  input pcpi_wait;
  input pcpi_wr;
  reg [31:0] reg_next_pc;
  reg [31:0] reg_op1;
  reg [31:0] reg_op2;
  reg [31:0] reg_out;
  reg [31:0] reg_pc;
  reg [4:0] reg_sh;
  input resetn;
  output [35:0] trace_data;
  reg [35:0] trace_data;
  output trace_valid;
  reg trace_valid;
  output trap;
  reg trap;
  assign _0111_ = reg_op1 + reg_op2;
  assign _0112_ = reg_pc + _0196_[2:0];
  assign _0113_ = count_cycle + 1'h1;
  assign _0114_ = _0103_ + _0197_[2:0];
  assign _0115_ = count_instr + 1'h1;
  assign _0116_ = _0103_ + decoded_imm_j;
  assign _0117_ = reg_pc + decoded_imm;
  assign _0118_ = reg_op1 + decoded_imm;
  assign _0119_ = next_pc[31:2] + 1'h0;
  assign _0120_ = reg_out & 32'hfffffffe;
  assign _0121_ = reg_op1 & reg_op2;
  assign _0122_ = _0599_ & 32'hfffffffe;
  assign _0123_ = mem_la_wstrb & { mem_la_write, mem_la_write, mem_la_write, mem_la_write };
  assign _0183_ = latched_rd[0] == 1'h0;
  assign _0184_ = latched_rd[1] == 1'h0;
  assign _0185_ = latched_rd[2] == 1'h0;
  assign _0186_ = latched_rd[3] == 1'h0;
  assign _0187_ = latched_rd[4] == 1'h0;
  assign _0188_ = latched_rd[0] == 1'h1;
  assign _0189_ = latched_rd[1] == 1'h1;
  assign _0190_ = latched_rd[2] == 1'h1;
  assign _0191_ = latched_rd[3] == 1'h1;
  assign _0192_ = latched_rd[4] == 1'h1;
  assign _0135_ = _0183_ & _0184_;
  assign _0136_ = _0186_ & _0187_;
  assign _0137_ = _0185_ & _0136_;
  assign _0138_ = _0135_ & _0137_;
  assign _0139_ = _0188_ & _0184_;
  assign _0140_ = _0139_ & _0137_;
  assign _0141_ = _0183_ & _0189_;
  assign _0142_ = _0141_ & _0137_;
  assign _0143_ = _0188_ & _0189_;
  assign _0144_ = _0143_ & _0137_;
  assign _0145_ = _0190_ & _0136_;
  assign _0146_ = _0135_ & _0145_;
  assign _0147_ = _0139_ & _0145_;
  assign _0148_ = _0141_ & _0145_;
  assign _0149_ = _0143_ & _0145_;
  assign _0150_ = _0191_ & _0187_;
  assign _0151_ = _0185_ & _0150_;
  assign _0152_ = _0135_ & _0151_;
  assign _0153_ = _0139_ & _0151_;
  assign _0154_ = _0141_ & _0151_;
  assign _0155_ = _0143_ & _0151_;
  assign _0156_ = _0190_ & _0150_;
  assign _0157_ = _0135_ & _0156_;
  assign _0158_ = _0139_ & _0156_;
  assign _0159_ = _0141_ & _0156_;
  assign _0160_ = _0143_ & _0156_;
  assign _0161_ = _0186_ & _0192_;
  assign _0162_ = _0185_ & _0161_;
  assign _0163_ = _0135_ & _0162_;
  assign _0164_ = _0139_ & _0162_;
  assign _0165_ = _0141_ & _0162_;
  assign _0166_ = _0143_ & _0162_;
  assign _0167_ = _0190_ & _0161_;
  assign _0168_ = _0135_ & _0167_;
  assign _0169_ = _0139_ & _0167_;
  assign _0170_ = _0141_ & _0167_;
  assign _0171_ = _0143_ & _0167_;
  assign _0172_ = _0191_ & _0192_;
  assign _0173_ = _0185_ & _0172_;
  assign _0174_ = _0135_ & _0173_;
  assign _0175_ = _0139_ & _0173_;
  assign _0176_ = _0141_ & _0173_;
  assign _0177_ = _0143_ & _0173_;
  assign _0178_ = _0190_ & _0172_;
  assign _0179_ = _0135_ & _0178_;
  assign _0180_ = _0139_ & _0178_;
  assign _0181_ = _0141_ & _0178_;
  assign _0182_ = _0143_ & _0178_;
  assign _0124_ = | { _0215_, _0216_, _0444_, _0445_, _0446_, _0447_, _0448_ };
  assign _0125_ = | { _0215_, _0216_, _0445_, _0446_, _0447_, _0448_ };
  assign _0126_ = | { _0215_, _0216_, _0445_, _0447_, _0448_ };
  assign _0127_ = | { _0215_, _0216_, _0444_, _0448_ };
  assign _0128_ = | { _0216_, _0444_, _0445_, _0446_, _0447_, _0448_ };
  assign _0129_ = | { _0216_, _0444_, _0448_ };
  assign _0130_ = | { is_lui_auipc_jal, is_slli_srli_srai, is_jalr_addi_slti_sltiu_xori_ori_andi };
  assign _0131_ = | { _0216_, _0445_, _0446_, _0447_, _0448_ };
  assign _0132_ = | { _0215_, _0216_, _0446_, _0448_ };
  assign _0133_ = | { latched_branch, _0292_ };
  assign _0134_ = | { _0562_, _0565_ };
  assign _0198_ = ! mem_rdata_q[14:12];
  assign _0199_ = mem_rdata_q[14:12] == 1'h1;
  assign _0200_ = mem_rdata_q[14:12] == 3'h4;
  assign _0201_ = mem_rdata_q[14:12] == 3'h5;
  assign _0202_ = mem_rdata_q[14:12] == 3'h6;
  assign _0203_ = mem_rdata_q[14:12] == 3'h7;
  assign _0204_ = mem_rdata_q[14:12] == 2'h2;
  assign _0205_ = mem_rdata_q[14:12] == 2'h3;
  assign _0206_ = ! mem_rdata_q[31:25];
  assign _0207_ = mem_rdata_q[31:25] == 6'h20;
  assign _0208_ = mem_rdata_q[6:0] == 7'h73;
  assign _0209_ = mem_rdata_q[31:12] == 20'hc0002;
  assign _0210_ = mem_rdata_q[31:12] == 20'hc0102;
  assign _0211_ = mem_rdata_q[31:12] == 20'hc8002;
  assign _0212_ = mem_rdata_q[31:12] == 20'hc8102;
  assign _0213_ = mem_rdata_q[31:12] == 20'hc0202;
  assign _0214_ = mem_rdata_q[31:12] == 20'hc8202;
  assign alu_eq = reg_op1 == reg_op2;
  assign _0215_ = cpu_state == 7'h40;
  assign _0216_ = cpu_state == 5'h10;
  assign _0217_ = ! reg_sh;
  assign _0218_ = ! mem_wordsize;
  assign _0219_ = mem_wordsize == 1'h1;
  assign _0220_ = mem_rdata_latched[6:0] == 6'h37;
  assign _0221_ = mem_rdata_latched[6:0] == 5'h17;
  assign _0222_ = mem_rdata_latched[6:0] == 7'h6f;
  assign _0223_ = mem_rdata_latched[6:0] == 7'h67;
  assign _0224_ = ! mem_rdata_latched[14:12];
  assign _0225_ = mem_rdata_latched[6:0] == 7'h63;
  assign _0226_ = mem_rdata_latched[6:0] == 2'h3;
  assign _0227_ = mem_rdata_latched[6:0] == 6'h23;
  assign _0228_ = mem_rdata_latched[6:0] == 5'h13;
  assign _0229_ = mem_rdata_latched[6:0] == 6'h33;
  assign _0230_ = reg_sh >= 3'h4;
  assign _0231_ = decoder_trigger && _0313_;
  assign _0232_ = is_beq_bne_blt_bge_bltu_bgeu && _0198_;
  assign _0233_ = is_beq_bne_blt_bge_bltu_bgeu && _0199_;
  assign _0234_ = is_beq_bne_blt_bge_bltu_bgeu && _0200_;
  assign _0235_ = is_beq_bne_blt_bge_bltu_bgeu && _0201_;
  assign _0236_ = is_beq_bne_blt_bge_bltu_bgeu && _0202_;
  assign _0237_ = is_beq_bne_blt_bge_bltu_bgeu && _0203_;
  assign _0238_ = is_lb_lh_lw_lbu_lhu && _0198_;
  assign _0239_ = is_lb_lh_lw_lbu_lhu && _0199_;
  assign _0240_ = is_lb_lh_lw_lbu_lhu && _0204_;
  assign _0241_ = is_lb_lh_lw_lbu_lhu && _0200_;
  assign _0242_ = is_lb_lh_lw_lbu_lhu && _0201_;
  assign _0243_ = is_sb_sh_sw && _0198_;
  assign _0244_ = is_sb_sh_sw && _0199_;
  assign _0245_ = is_alu_reg_imm && _0198_;
  assign _0246_ = is_alu_reg_imm && _0204_;
  assign _0247_ = is_alu_reg_imm && _0205_;
  assign _0248_ = is_alu_reg_imm && _0200_;
  assign _0249_ = is_alu_reg_imm && _0202_;
  assign _0250_ = is_alu_reg_imm && _0203_;
  assign _0251_ = is_alu_reg_imm && _0199_;
  assign _0252_ = _0251_ && _0206_;
  assign _0253_ = is_alu_reg_imm && _0201_;
  assign _0254_ = _0253_ && _0206_;
  assign _0255_ = _0253_ && _0207_;
  assign _0256_ = is_alu_reg_reg && _0198_;
  assign _0257_ = _0256_ && _0206_;
  assign _0258_ = _0256_ && _0207_;
  assign _0259_ = is_alu_reg_reg && _0199_;
  assign _0260_ = _0259_ && _0206_;
  assign _0261_ = is_alu_reg_reg && _0204_;
  assign _0262_ = _0261_ && _0206_;
  assign _0263_ = is_alu_reg_reg && _0205_;
  assign _0264_ = _0263_ && _0206_;
  assign _0265_ = is_alu_reg_reg && _0200_;
  assign _0266_ = _0265_ && _0206_;
  assign _0267_ = is_alu_reg_reg && _0201_;
  assign _0268_ = _0267_ && _0206_;
  assign _0269_ = _0267_ && _0207_;
  assign _0270_ = is_alu_reg_reg && _0202_;
  assign _0271_ = _0270_ && _0206_;
  assign _0272_ = is_alu_reg_reg && _0203_;
  assign _0273_ = _0272_ && _0206_;
  assign _0274_ = _0208_ && _0209_;
  assign _0275_ = _0208_ && _0210_;
  assign _0277_ = _0208_ && _0211_;
  assign _0278_ = _0208_ && _0212_;
  assign _0280_ = _0208_ && _0213_;
  assign _0281_ = _0208_ && _0214_;
  assign _0282_ = _0208_ && _0314_;
  assign _0283_ = _0282_ && _0315_;
  assign _0284_ = _0199_ && _0206_;
  assign _0285_ = _0201_ && _0206_;
  assign _0286_ = _0201_ && _0207_;
  assign _0287_ = is_alu_reg_imm && _0589_;
  assign _0288_ = is_alu_reg_imm && _0590_;
  assign _0289_ = latched_store && latched_branch;
  assign _0292_ = latched_store && _0319_;
  assign _0293_ = resetn && cpuregs_write;
  assign _0294_ = _0293_ && latched_rd;
  assign _0295_ = mem_do_rinst && mem_done;
  assign _0296_ = _0320_ && _0321_;
  assign _0297_ = _0322_ && _0323_;
  assign _0298_ = _0324_ && mem_done;
  assign _0299_ = resetn && _0337_;
  assign _0300_ = _0218_ && _0442_;
  assign _0301_ = _0219_ && reg_op1[0];
  assign _0302_ = resetn && mem_do_rinst;
  assign _0303_ = _0302_ && _0591_;
  assign _0304_ = decoder_trigger_q && _0325_;
  assign _0305_ = _0304_ && instr_ecall_ebreak;
  assign mem_xfer = mem_valid && mem_ready;
  assign _0306_ = mem_xfer && _0592_;
  assign _0307_ = _0306_ && _0340_;
  assign _0308_ = _0587_ && mem_do_rinst;
  assign mem_done = resetn && _0341_;
  assign _0309_ = resetn && _0310_;
  assign mem_la_write = _0309_ && mem_do_wdata;
  assign _0311_ = _0310_ && _0343_;
  assign mem_la_read = resetn && _0311_;
  assign _0312_ = _0223_ && _0224_;
  assign _0313_ = ! decoder_pseudo_trigger;
  assign _0314_ = ! mem_rdata_q[31:21];
  assign _0315_ = ! mem_rdata_q[19:7];
  assign _0316_ = ! alu_eq;
  assign _0317_ = ! alu_lts;
  assign _0318_ = ! alu_ltu;
  assign _0319_ = ! latched_branch;
  assign _0320_ = ! decoder_trigger;
  assign _0321_ = ! trace_valid;
  assign _0322_ = ! instr_jalr;
  assign _0323_ = ! instr_retirq;
  assign _0324_ = ! mem_do_prefetch;
  assign _0325_ = ! decoder_pseudo_trigger_q;
  assign _0326_ = ! resetn;
  assign _0310_ = ! mem_state;
  assign _0276_ = _0274_ || _0275_;
  assign _0279_ = _0277_ || _0278_;
  assign _0327_ = instr_jalr || _0288_;
  assign _0328_ = instr_sra || instr_srai;
  assign _0329_ = instr_xori || instr_xor;
  assign _0330_ = instr_ori || instr_or;
  assign _0331_ = instr_andi || instr_and;
  assign _0290_ = instr_sll || instr_slli;
  assign _0332_ = instr_srl || instr_srli;
  assign _0333_ = _0332_ || instr_sra;
  assign _0291_ = _0333_ || instr_srai;
  assign _0334_ = _0324_ || mem_done;
  assign _0335_ = instr_lb || instr_lbu;
  assign _0336_ = instr_lh || instr_lhu;
  assign _0337_ = mem_do_rdata || mem_do_wdata;
  assign _0338_ = _0326_ || mem_done;
  assign _0339_ = mem_do_rinst || mem_do_rdata;
  assign _0340_ = _0339_ || mem_do_wdata;
  assign _0341_ = _0307_ || _0308_;
  assign _0342_ = mem_do_rinst || mem_do_prefetch;
  assign _0343_ = _0342_ || mem_do_rdata;
  assign _0344_ = _0326_ || trap;
  assign _0345_ = _0326_ || mem_ready;
  assign _0346_ = mem_la_read || mem_la_write;
  assign alu_lts = $signed(reg_op1) < $signed(reg_op2);
  assign alu_ltu = reg_op1 < reg_op2;
  assign _0441_ = decoded_rs[4] ? _0348_ : _0347_;
  assign _0347_ = decoded_rs[3] ? _0350_ : _0349_;
  assign _0348_ = decoded_rs[3] ? _0352_ : _0351_;
  assign _0349_ = decoded_rs[2] ? _0354_ : _0353_;
  assign _0350_ = decoded_rs[2] ? _0356_ : _0355_;
  assign _0351_ = decoded_rs[2] ? _0358_ : _0357_;
  assign _0352_ = decoded_rs[2] ? _0360_ : _0359_;
  assign _0353_ = decoded_rs[1] ? _0362_ : _0361_;
  assign _0354_ = decoded_rs[1] ? _0364_ : _0363_;
  assign _0355_ = decoded_rs[1] ? _0366_ : _0365_;
  assign _0356_ = decoded_rs[1] ? _0368_ : _0367_;
  assign _0357_ = decoded_rs[1] ? _0370_ : _0369_;
  assign _0358_ = decoded_rs[1] ? _0372_ : _0371_;
  assign _0359_ = decoded_rs[1] ? _0374_ : _0373_;
  assign _0360_ = decoded_rs[1] ? _0376_ : _0375_;
  assign _0361_ = decoded_rs[0] ? \cpuregs[1]  : \cpuregs[0] ;
  assign _0371_ = decoded_rs[0] ? \cpuregs[21]  : \cpuregs[20] ;
  assign _0372_ = decoded_rs[0] ? \cpuregs[23]  : \cpuregs[22] ;
  assign _0373_ = decoded_rs[0] ? \cpuregs[25]  : \cpuregs[24] ;
  assign _0374_ = decoded_rs[0] ? \cpuregs[27]  : \cpuregs[26] ;
  assign _0375_ = decoded_rs[0] ? \cpuregs[29]  : \cpuregs[28] ;
  assign _0376_ = decoded_rs[0] ? \cpuregs[31]  : \cpuregs[30] ;
  assign _0362_ = decoded_rs[0] ? \cpuregs[3]  : \cpuregs[2] ;
  assign _0363_ = decoded_rs[0] ? \cpuregs[5]  : \cpuregs[4] ;
  assign _0364_ = decoded_rs[0] ? \cpuregs[7]  : \cpuregs[6] ;
  assign _0365_ = decoded_rs[0] ? \cpuregs[9]  : \cpuregs[8] ;
  assign _0366_ = decoded_rs[0] ? \cpuregs[11]  : \cpuregs[10] ;
  assign _0367_ = decoded_rs[0] ? \cpuregs[13]  : \cpuregs[12] ;
  assign _0368_ = decoded_rs[0] ? \cpuregs[15]  : \cpuregs[14] ;
  assign _0369_ = decoded_rs[0] ? \cpuregs[17]  : \cpuregs[16] ;
  assign _0370_ = decoded_rs[0] ? \cpuregs[19]  : \cpuregs[18] ;
  assign _0377_ = _0138_ & _0000_[31];
  assign _0378_ = _0154_ & _0000_[31];
  assign _0379_ = _0155_ & _0000_[31];
  assign _0380_ = _0157_ & _0000_[31];
  assign _0381_ = _0158_ & _0000_[31];
  assign _0382_ = _0159_ & _0000_[31];
  assign _0383_ = _0160_ & _0000_[31];
  assign _0384_ = _0163_ & _0000_[31];
  assign _0385_ = _0164_ & _0000_[31];
  assign _0386_ = _0165_ & _0000_[31];
  assign _0387_ = _0166_ & _0000_[31];
  assign _0388_ = _0140_ & _0000_[31];
  assign _0389_ = _0168_ & _0000_[31];
  assign _0390_ = _0169_ & _0000_[31];
  assign _0391_ = _0170_ & _0000_[31];
  assign _0392_ = _0171_ & _0000_[31];
  assign _0393_ = _0174_ & _0000_[31];
  assign _0394_ = _0175_ & _0000_[31];
  assign _0395_ = _0176_ & _0000_[31];
  assign _0396_ = _0177_ & _0000_[31];
  assign _0397_ = _0179_ & _0000_[31];
  assign _0398_ = _0180_ & _0000_[31];
  assign _0399_ = _0142_ & _0000_[31];
  assign _0400_ = _0181_ & _0000_[31];
  assign _0401_ = _0182_ & _0000_[31];
  assign _0402_ = _0144_ & _0000_[31];
  assign _0403_ = _0146_ & _0000_[31];
  assign _0404_ = _0147_ & _0000_[31];
  assign _0405_ = _0148_ & _0000_[31];
  assign _0406_ = _0149_ & _0000_[31];
  assign _0407_ = _0152_ & _0000_[31];
  assign _0408_ = _0153_ & _0000_[31];
  assign _0409_ = _0377_ ? cpuregs_wrdata : \cpuregs[0] ;
  assign _0410_ = _0378_ ? cpuregs_wrdata : \cpuregs[10] ;
  assign _0411_ = _0379_ ? cpuregs_wrdata : \cpuregs[11] ;
  assign _0412_ = _0380_ ? cpuregs_wrdata : \cpuregs[12] ;
  assign _0413_ = _0381_ ? cpuregs_wrdata : \cpuregs[13] ;
  assign _0414_ = _0382_ ? cpuregs_wrdata : \cpuregs[14] ;
  assign _0415_ = _0383_ ? cpuregs_wrdata : \cpuregs[15] ;
  assign _0416_ = _0384_ ? cpuregs_wrdata : \cpuregs[16] ;
  assign _0417_ = _0385_ ? cpuregs_wrdata : \cpuregs[17] ;
  assign _0418_ = _0386_ ? cpuregs_wrdata : \cpuregs[18] ;
  assign _0419_ = _0387_ ? cpuregs_wrdata : \cpuregs[19] ;
  assign _0420_ = _0388_ ? cpuregs_wrdata : \cpuregs[1] ;
  assign _0421_ = _0389_ ? cpuregs_wrdata : \cpuregs[20] ;
  assign _0422_ = _0390_ ? cpuregs_wrdata : \cpuregs[21] ;
  assign _0423_ = _0391_ ? cpuregs_wrdata : \cpuregs[22] ;
  assign _0424_ = _0392_ ? cpuregs_wrdata : \cpuregs[23] ;
  assign _0425_ = _0393_ ? cpuregs_wrdata : \cpuregs[24] ;
  assign _0426_ = _0394_ ? cpuregs_wrdata : \cpuregs[25] ;
  assign _0427_ = _0395_ ? cpuregs_wrdata : \cpuregs[26] ;
  assign _0428_ = _0396_ ? cpuregs_wrdata : \cpuregs[27] ;
  assign _0429_ = _0397_ ? cpuregs_wrdata : \cpuregs[28] ;
  assign _0430_ = _0398_ ? cpuregs_wrdata : \cpuregs[29] ;
  assign _0431_ = _0399_ ? cpuregs_wrdata : \cpuregs[2] ;
  assign _0432_ = _0400_ ? cpuregs_wrdata : \cpuregs[30] ;
  assign _0433_ = _0401_ ? cpuregs_wrdata : \cpuregs[31] ;
  assign _0434_ = _0402_ ? cpuregs_wrdata : \cpuregs[3] ;
  assign _0435_ = _0403_ ? cpuregs_wrdata : \cpuregs[4] ;
  assign _0436_ = _0404_ ? cpuregs_wrdata : \cpuregs[5] ;
  assign _0437_ = _0405_ ? cpuregs_wrdata : \cpuregs[6] ;
  assign _0438_ = _0406_ ? cpuregs_wrdata : \cpuregs[7] ;
  assign _0439_ = _0407_ ? cpuregs_wrdata : \cpuregs[8] ;
  assign _0440_ = _0408_ ? cpuregs_wrdata : \cpuregs[9] ;
  always @(posedge clk)
      \cpuregs[0]  <= _0409_;
  always @(posedge clk)
      \cpuregs[10]  <= _0410_;
  always @(posedge clk)
      \cpuregs[11]  <= _0411_;
  always @(posedge clk)
      \cpuregs[12]  <= _0412_;
  always @(posedge clk)
      \cpuregs[13]  <= _0413_;
  always @(posedge clk)
      \cpuregs[14]  <= _0414_;
  always @(posedge clk)
      \cpuregs[15]  <= _0415_;
  always @(posedge clk)
      \cpuregs[16]  <= _0416_;
  always @(posedge clk)
      \cpuregs[17]  <= _0417_;
  always @(posedge clk)
      \cpuregs[18]  <= _0418_;
  always @(posedge clk)
      \cpuregs[19]  <= _0419_;
  always @(posedge clk)
      \cpuregs[1]  <= _0420_;
  always @(posedge clk)
      \cpuregs[20]  <= _0421_;
  always @(posedge clk)
      \cpuregs[21]  <= _0422_;
  always @(posedge clk)
      \cpuregs[22]  <= _0423_;
  always @(posedge clk)
      \cpuregs[23]  <= _0424_;
  always @(posedge clk)
      \cpuregs[24]  <= _0425_;
  always @(posedge clk)
      \cpuregs[25]  <= _0426_;
  always @(posedge clk)
      \cpuregs[26]  <= _0427_;
  always @(posedge clk)
      \cpuregs[27]  <= _0428_;
  always @(posedge clk)
      \cpuregs[28]  <= _0429_;
  always @(posedge clk)
      \cpuregs[29]  <= _0430_;
  always @(posedge clk)
      \cpuregs[2]  <= _0431_;
  always @(posedge clk)
      \cpuregs[30]  <= _0432_;
  always @(posedge clk)
      \cpuregs[31]  <= _0433_;
  always @(posedge clk)
      \cpuregs[3]  <= _0434_;
  always @(posedge clk)
      \cpuregs[4]  <= _0435_;
  always @(posedge clk)
      \cpuregs[5]  <= _0436_;
  always @(posedge clk)
      \cpuregs[6]  <= _0437_;
  always @(posedge clk)
      \cpuregs[7]  <= _0438_;
  always @(posedge clk)
      \cpuregs[8]  <= _0439_;
  always @(posedge clk)
      \cpuregs[9]  <= _0440_;
  assign _0442_ = | reg_op1[1:0];
  assign _0443_ = reg_op1 | reg_op2;
  always @(posedge clk)
      trap <= _0097_;
  always @(posedge clk)
      pcpi_valid <= _0087_;
  always @(posedge clk)
      eoi <= _0012_;
  always @(posedge clk)
      trace_valid <= 1'h0;
  always @(posedge clk)
      trace_data <= 36'h0xxxxxxxx;
  always @(posedge clk)
      count_cycle <= _0002_;
  always @(posedge clk)
      count_instr <= _0003_;
  always @(posedge clk)
      reg_pc <= _0092_;
  always @(posedge clk)
      reg_next_pc <= _0088_;
  always @(posedge clk)
      reg_op1 <= _0089_;
  always @(posedge clk)
      reg_op2 <= _0090_;
  always @(posedge clk)
      reg_out <= _0091_;
  always @(posedge clk)
      reg_sh <= _0093_;
  always @(posedge clk)
      mem_wordsize <= _0085_;
  always @(posedge clk)
      mem_do_prefetch <= _0076_;
  always @(posedge clk)
      mem_do_rinst <= _0078_;
  always @(posedge clk)
      mem_do_rdata <= _0077_;
  always @(posedge clk)
      mem_do_wdata <= _0079_;
  always @(posedge clk)
      decoder_trigger <= _0011_;
  always @(posedge clk)
      decoder_trigger_q <= decoder_trigger;
  always @(posedge clk)
      decoder_pseudo_trigger <= _0010_;
  always @(posedge clk)
      decoder_pseudo_trigger_q <= decoder_pseudo_trigger;
  always @(posedge clk)
      cpu_state <= _0004_;
  always @(posedge clk)
      latched_store <= _0074_;
  always @(posedge clk)
      latched_stalu <= _0073_;
  always @(posedge clk)
      latched_branch <= _0068_;
  always @(posedge clk)
      latched_compr <= _0069_;
  always @(posedge clk)
      latched_is_lu <= _0071_;
  always @(posedge clk)
      latched_is_lh <= _0070_;
  always @(posedge clk)
      latched_rd <= _0072_;
  always @(posedge clk)
      alu_out_q <= alu_out;
  always @(posedge clk)
      instr_lui <= _0031_;
  always @(posedge clk)
      instr_auipc <= _0017_;
  always @(posedge clk)
      instr_jal <= _0025_;
  always @(posedge clk)
      instr_jalr <= _0026_;
  always @(posedge clk)
      instr_beq <= _0018_;
  always @(posedge clk)
      instr_bne <= _0023_;
  always @(posedge clk)
      instr_blt <= _0021_;
  always @(posedge clk)
      instr_bge <= _0019_;
  always @(posedge clk)
      instr_bltu <= _0022_;
  always @(posedge clk)
      instr_bgeu <= _0020_;
  always @(posedge clk)
      instr_lb <= _0027_;
  always @(posedge clk)
      instr_lh <= _0029_;
  always @(posedge clk)
      instr_lw <= _0032_;
  always @(posedge clk)
      instr_lbu <= _0028_;
  always @(posedge clk)
      instr_lhu <= _0030_;
  always @(posedge clk)
      instr_sb <= _0040_;
  always @(posedge clk)
      instr_sh <= _0041_;
  always @(posedge clk)
      instr_addi <= _0014_;
  always @(posedge clk)
      instr_slti <= _0045_;
  always @(posedge clk)
      instr_sltiu <= _0046_;
  always @(posedge clk)
      instr_xori <= _0054_;
  always @(posedge clk)
      instr_ori <= _0034_;
  always @(posedge clk)
      instr_andi <= _0016_;
  always @(posedge clk)
      instr_slli <= _0043_;
  always @(posedge clk)
      instr_srli <= _0051_;
  always @(posedge clk)
      instr_srai <= _0049_;
  always @(posedge clk)
      instr_add <= _0013_;
  always @(posedge clk)
      instr_sub <= _0052_;
  always @(posedge clk)
      instr_sll <= _0042_;
  always @(posedge clk)
      instr_slt <= _0044_;
  always @(posedge clk)
      instr_sltu <= _0047_;
  always @(posedge clk)
      instr_xor <= _0053_;
  always @(posedge clk)
      instr_srl <= _0050_;
  always @(posedge clk)
      instr_sra <= _0048_;
  always @(posedge clk)
      instr_or <= _0033_;
  always @(posedge clk)
      instr_and <= _0015_;
  always @(posedge clk)
      instr_rdcycle <= _0035_;
  always @(posedge clk)
      instr_rdcycleh <= _0036_;
  always @(posedge clk)
      instr_rdinstr <= _0037_;
  always @(posedge clk)
      instr_rdinstrh <= _0038_;
  always @(posedge clk)
      instr_ecall_ebreak <= _0024_;
  always @(posedge clk)
      instr_retirq <= _0039_;
  always @(posedge clk)
      decoded_rd <= _0007_;
  always @(posedge clk)
      decoded_rs1 <= _0008_;
  always @(posedge clk)
      decoded_rs2 <= _0009_;
  always @(posedge clk)
      decoded_imm <= _0005_;
  always @(posedge clk)
      decoded_imm_j <= _0006_;
  always @(posedge clk)
      compressed_instr <= _0001_;
  always @(posedge clk)
      is_lui_auipc_jal <= _0062_;
  always @(posedge clk)
      is_lb_lh_lw_lbu_lhu <= _0060_;
  always @(posedge clk)
      is_slli_srli_srai <= _0065_;
  always @(posedge clk)
      is_jalr_addi_slti_sltiu_xori_ori_andi <= _0059_;
  always @(posedge clk)
      is_sb_sh_sw <= _0064_;
  always @(posedge clk)
      is_lui_auipc_jal_jalr_addi_add_sub <= _0063_;
  always @(posedge clk)
      is_slti_blt_slt <= _0066_;
  always @(posedge clk)
      is_sltiu_bltu_sltu <= _0067_;
  always @(posedge clk)
      is_beq_bne_blt_bge_bltu_bgeu <= _0057_;
  always @(posedge clk)
      is_lbu_lhu_lw <= _0061_;
  always @(posedge clk)
      is_alu_reg_imm <= _0055_;
  always @(posedge clk)
      is_alu_reg_reg <= _0056_;
  always @(posedge clk)
      is_compare <= _0058_;
  always @(posedge clk)
      mem_valid <= _0083_;
  always @(posedge clk)
      mem_instr <= _0080_;
  always @(posedge clk)
      mem_addr <= _0075_;
  always @(posedge clk)
      mem_wdata <= _0084_;
  always @(posedge clk)
      mem_wstrb <= _0086_;
  always @(posedge clk)
      mem_state <= _0082_;
  always @(posedge clk)
      mem_rdata_q <= _0081_;
  assign _0103_ = latched_branch ? _0600_ : reg_next_pc;
  assign _0102_ = _0444_ ? _0107_ : 1'h0;
  assign _0444_ = cpu_state == 2'h2;
  assign _0100_ = _0124_ ? 1'h0 : _0105_;
  assign _0445_ = cpu_state == 3'h4;
  assign _0446_ = cpu_state == 4'h8;
  assign _0447_ = cpu_state == 6'h20;
  assign _0448_ = cpu_state == 8'h80;
  assign _0101_ = _0446_ ? _0106_ : 1'h0;
  assign _0096_ = resetn ? _0102_ : 1'h0;
  assign _0094_ = resetn ? _0100_ : 1'h0;
  assign _0095_ = resetn ? _0101_ : 1'h0;
  assign _0449_ = _0298_ ? 1'h1 : 1'h0;
  assign _0450_ = _0334_ ? _0449_ : 1'h0;
  assign _0451_ = _0125_ ? 1'h0 : _0450_;
  assign _0010_ = resetn ? _0451_ : 1'h0;
  assign _0452_ = _0298_ ? 1'h1 : _0295_;
  assign _0453_ = _0334_ ? _0452_ : _0295_;
  function [0:0] _1089_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1089_ = b[0:0];
      2'b1?:
        _1089_ = b[1:1];
      default:
        _1089_ = a;
    endcase
  endfunction
  assign _0454_ = _1089_(_0453_, { _0456_, _0295_ }, { _0446_, _0126_ });
  assign _0455_ = alu_out_0 ? 1'h0 : _0295_;
  assign _0456_ = is_beq_bne_blt_bge_bltu_bgeu ? _0455_ : _0295_;
  assign _0011_ = resetn ? _0454_ : _0295_;
  function [31:0] _1093_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1093_ = b[31:0];
      2'b1?:
        _1093_ = b[63:32];
      default:
        _1093_ = a;
    endcase
  endfunction
  assign _0457_ = _1093_({ mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7], mem_rdata_word[7:0] }, { mem_rdata_word, mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15], mem_rdata_word[15:0] }, { latched_is_lu, latched_is_lh });
  function [31:0] _1094_;
    input [31:0] a;
    input [127:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _1094_ = b[31:0];
      4'b??1?:
        _1094_ = b[63:32];
      4'b?1??:
        _1094_ = b[95:64];
      4'b1???:
        _1094_ = b[127:96];
      default:
        _1094_ = a;
    endcase
  endfunction
  assign _0091_ = _1094_(_0457_, { _0458_, _0117_, reg_op1, 32'hxxxxxxxx }, { _0447_, _0446_, _0445_, _0127_ });
  function [31:0] _1095_;
    input [31:0] a;
    input [95:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _1095_ = b[31:0];
      3'b?1?:
        _1095_ = b[63:32];
      3'b1??:
        _1095_ = b[95:64];
      default:
        _1095_ = a;
    endcase
  endfunction
  assign _0458_ = _1095_(count_instr[63:32], { count_cycle[31:0], count_cycle[63:32], count_instr[31:0] }, { instr_rdcycle, instr_rdcycleh, instr_rdinstr });
  assign _0459_ = _0230_ ? _0195_[4:0] : _0597_[4:0];
  function [4:0] _1097_;
    input [4:0] a;
    input [9:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1097_ = b[4:0];
      2'b1?:
        _1097_ = b[9:5];
      default:
        _1097_ = a;
    endcase
  endfunction
  assign _0093_ = _1097_(5'hxx, { cpuregs_rs1[4:0], _0459_ }, { _0216_, _0445_ });
  assign _0460_ = _0448_ ? 1'h1 : 1'h0;
  assign _0097_ = resetn ? _0460_ : 1'h0;
  assign _0461_ = is_beq_bne_blt_bge_bltu_bgeu ? 5'h00 : latched_rd;
  function [4:0] _1101_;
    input [4:0] a;
    input [9:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1101_ = b[4:0];
      2'b1?:
        _1101_ = b[9:5];
      default:
        _1101_ = a;
    endcase
  endfunction
  assign _0462_ = _1101_(latched_rd, { decoded_rd, _0461_ }, { _0215_, _0446_ });
  assign _0072_ = resetn ? _0462_ : latched_rd;
  assign _0463_ = mem_do_rdata ? latched_is_lh : instr_lh;
  assign _0464_ = _0334_ ? _0463_ : latched_is_lh;
  function [0:0] _1105_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1105_ = b[0:0];
      2'b1?:
        _1105_ = b[1:1];
      default:
        _1105_ = a;
    endcase
  endfunction
  assign _0465_ = _1105_(_0464_, { 1'h0, latched_is_lh }, { _0215_, _0128_ });
  assign _0070_ = resetn ? _0465_ : 1'h0;
  assign _0466_ = mem_do_rdata ? latched_is_lu : is_lbu_lhu_lw;
  assign _0467_ = _0334_ ? _0466_ : latched_is_lu;
  function [0:0] _1109_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1109_ = b[0:0];
      2'b1?:
        _1109_ = b[1:1];
      default:
        _1109_ = a;
    endcase
  endfunction
  assign _0468_ = _1109_(_0467_, { 1'h0, latched_is_lu }, { _0215_, _0128_ });
  assign _0071_ = resetn ? _0468_ : 1'h0;
  assign _0469_ = _0215_ ? compressed_instr : latched_compr;
  assign _0069_ = resetn ? _0469_ : latched_compr;
  assign _0470_ = is_beq_bne_blt_bge_bltu_bgeu ? alu_out_0 : instr_jalr;
  function [0:0] _1114_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1114_ = b[0:0];
      2'b1?:
        _1114_ = b[1:1];
      default:
        _1114_ = a;
    endcase
  endfunction
  assign _0471_ = _1114_(latched_branch, { _0473_, _0470_ }, { _0215_, _0446_ });
  assign _0472_ = instr_jal ? 1'h1 : 1'h0;
  assign _0473_ = decoder_trigger ? _0472_ : 1'h0;
  assign _0068_ = resetn ? _0471_ : 1'h0;
  assign _0474_ = is_beq_bne_blt_bge_bltu_bgeu ? latched_stalu : 1'h1;
  function [0:0] _1119_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1119_ = b[0:0];
      2'b1?:
        _1119_ = b[1:1];
      default:
        _1119_ = a;
    endcase
  endfunction
  assign _0475_ = _1119_(latched_stalu, { 1'h0, _0474_ }, { _0215_, _0446_ });
  assign _0073_ = resetn ? _0475_ : 1'h0;
  function [0:0] _1121_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _1121_ = b[0:0];
      4'b??1?:
        _1121_ = b[1:1];
      4'b?1??:
        _1121_ = b[2:2];
      4'b1???:
        _1121_ = b[3:3];
      default:
        _1121_ = a;
    endcase
  endfunction
  assign _0476_ = _1121_(1'h1, { 1'h0, _0478_, _0477_, latched_store }, { _0215_, _0447_, _0446_, _0129_ });
  assign _0477_ = is_beq_bne_blt_bge_bltu_bgeu ? alu_out_0 : 1'h1;
  assign _0478_ = is_rdcycle_rdcycleh_rdinstr_rdinstrh ? 1'h1 : latched_store;
  assign _0074_ = resetn ? _0476_ : 1'h0;
  assign _0479_ = _0298_ ? 8'h40 : cpu_state;
  assign _0480_ = _0334_ ? _0479_ : cpu_state;
  function [7:0] _1127_;
    input [7:0] a;
    input [47:0] b;
    input [5:0] s;
    casez (s) // synopsys parallel_case
      6'b?????1:
        _1127_ = b[7:0];
      6'b????1?:
        _1127_ = b[15:8];
      6'b???1??:
        _1127_ = b[23:16];
      6'b??1???:
        _1127_ = b[31:24];
      6'b?1????:
        _1127_ = b[39:32];
      6'b1?????:
        _1127_ = b[47:40];
      default:
        _1127_ = a;
    endcase
  endfunction
  assign _0481_ = _1127_(_0480_, { cpu_state, _0487_, 1'h0, _0194_[6:0], 4'h0, _0193_[3:0], _0484_, _0482_ }, { _0448_, _0215_, _0447_, _0216_, _0446_, _0445_ });
  assign _0482_ = _0217_ ? 8'h40 : cpu_state;
  assign _0483_ = mem_done ? 8'h40 : cpu_state;
  assign _0484_ = is_beq_bne_blt_bge_bltu_bgeu ? _0483_ : 8'h40;
  assign _0193_[3:0] = is_sb_sh_sw ? 4'h2 : 4'h8;
  function [6:0] _1132_;
    input [6:0] a;
    input [20:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _1132_ = b[6:0];
      3'b?1?:
        _1132_ = b[13:7];
      3'b1??:
        _1132_ = b[20:14];
      default:
        _1132_ = a;
    endcase
  endfunction
  assign _0194_[6:0] = _1132_(7'h10, 21'h100088, { is_rdcycle_rdcycleh_rdinstr_rdinstrh, is_lb_lh_lw_lbu_lhu, _0130_ });
  assign _0485_ = | { is_slli_srli_srai, is_jalr_addi_slti_sltiu_xori_ori_andi };
  assign _0486_ = instr_jal ? cpu_state : 8'h20;
  assign _0487_ = decoder_trigger ? _0486_ : cpu_state;
  assign _0488_ = resetn ? _0481_ : 8'h40;
  assign _0489_ = _0300_ ? 8'h80 : _0488_;
  assign _0490_ = _0301_ ? 8'h80 : _0489_;
  assign _0491_ = _0299_ ? _0490_ : _0488_;
  assign _0492_ = _0303_ ? 8'h80 : _0491_;
  assign _0004_ = _0305_ ? 8'h80 : _0492_;
  assign _0493_ = _0338_ ? 1'h0 : mem_do_wdata;
  assign _0079_ = _0096_ ? 1'h1 : _0493_;
  assign _0494_ = _0338_ ? 1'h0 : mem_do_rdata;
  assign _0077_ = _0094_ ? 1'h1 : _0494_;
  assign _0495_ = _0217_ ? mem_do_prefetch : mem_do_rinst;
  function [0:0] _1147_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _1147_ = b[0:0];
      4'b??1?:
        _1147_ = b[1:1];
      4'b?1??:
        _1147_ = b[2:2];
      4'b1???:
        _1147_ = b[3:3];
      default:
        _1147_ = a;
    endcase
  endfunction
  assign _0496_ = _1147_(mem_do_rinst, { _0499_, _0498_, _0497_, _0495_ }, { _0215_, _0447_, _0216_, _0445_ });
  assign _0497_ = is_sb_sh_sw ? 1'h1 : mem_do_prefetch;
  function [0:0] _1149_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1149_ = b[0:0];
      2'b1?:
        _1149_ = b[1:1];
      default:
        _1149_ = a;
    endcase
  endfunction
  assign _0498_ = _1149_(mem_do_rinst, { 1'h1, mem_do_prefetch }, { is_lb_lh_lw_lbu_lhu, _0130_ });
  assign _0499_ = decoder_trigger ? _0472_ : _0296_;
  assign _0500_ = resetn ? _0496_ : mem_do_rinst;
  assign _0501_ = _0338_ ? 1'h0 : _0500_;
  assign _0078_ = _0095_ ? 1'h1 : _0501_;
  assign _0502_ = instr_jal ? mem_do_prefetch : _0297_;
  assign _0503_ = decoder_trigger ? _0502_ : mem_do_prefetch;
  assign _0504_ = _0215_ ? _0503_ : mem_do_prefetch;
  assign _0505_ = resetn ? _0504_ : mem_do_prefetch;
  assign _0076_ = _0338_ ? 1'h0 : _0505_;
  function [1:0] _1159_;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1159_ = b[1:0];
      2'b1?:
        _1159_ = b[3:2];
      default:
        _1159_ = a;
    endcase
  endfunction
  assign _0506_ = _1159_(2'h0, 4'h9, { _0335_, _0336_ });
  assign _0507_ = mem_do_rdata ? mem_wordsize : _0506_;
  assign _0508_ = _0334_ ? _0507_ : mem_wordsize;
  function [1:0] _1162_;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1162_ = b[1:0];
      2'b1?:
        _1162_ = b[3:2];
      default:
        _1162_ = a;
    endcase
  endfunction
  assign _0509_ = _1162_(2'h0, 4'h9, { instr_sb, instr_sh });
  assign _0510_ = mem_do_wdata ? mem_wordsize : _0509_;
  assign _0511_ = _0334_ ? _0510_ : mem_wordsize;
  function [1:0] _1165_;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _1165_ = b[1:0];
      3'b?1?:
        _1165_ = b[3:2];
      3'b1??:
        _1165_ = b[5:4];
      default:
        _1165_ = a;
    endcase
  endfunction
  assign _0512_ = _1165_(_0508_, { 2'h0, mem_wordsize, _0511_ }, { _0215_, _0131_, _0444_ });
  assign _0085_ = resetn ? _0512_ : mem_wordsize;
  function [31:0] _1167_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1167_ = b[31:0];
      2'b1?:
        _1167_ = b[63:32];
      default:
        _1167_ = a;
    endcase
  endfunction
  assign _0513_ = _1167_(reg_op2, { _0514_, cpuregs_rs1 }, { _0447_, _0216_ });
  function [31:0] _1168_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1168_ = b[31:0];
      2'b1?:
        _1168_ = b[63:32];
      default:
        _1168_ = a;
    endcase
  endfunction
  assign _0514_ = _1168_(32'hxxxxxxxx, { decoded_imm, _0602_ }, { is_lui_auipc_jal, _0485_ });
  assign _0090_ = resetn ? _0513_ : reg_op2;
  assign _0515_ = mem_do_rdata ? reg_op1 : _0118_;
  assign _0516_ = _0334_ ? _0515_ : reg_op1;
  assign _0517_ = mem_do_wdata ? reg_op1 : _0118_;
  assign _0518_ = _0334_ ? _0517_ : reg_op1;
  function [31:0] _1174_;
    input [31:0] a;
    input [127:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _1174_ = b[31:0];
      4'b??1?:
        _1174_ = b[63:32];
      4'b?1??:
        _1174_ = b[95:64];
      4'b1???:
        _1174_ = b[127:96];
      default:
        _1174_ = a;
    endcase
  endfunction
  assign _0519_ = _1174_(_0516_, { _0524_, reg_op1, _0523_, _0518_ }, { _0447_, _0132_, _0445_, _0444_ });
  function [31:0] _1175_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1175_ = b[31:0];
      2'b1?:
        _1175_ = b[63:32];
      default:
        _1175_ = a;
    endcase
  endfunction
  assign _0520_ = _1175_({ reg_op1[31], reg_op1[31:1] }, { reg_op1[30:0], 2'h0, reg_op1[31:1] }, { _0290_, _0332_ });
  function [31:0] _1176_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1176_ = b[31:0];
      2'b1?:
        _1176_ = b[63:32];
      default:
        _1176_ = a;
    endcase
  endfunction
  assign _0521_ = _1176_({ reg_op1[31], reg_op1[31], reg_op1[31], reg_op1[31], reg_op1[31:4] }, { reg_op1[27:0], 8'h00, reg_op1[31:4] }, { _0290_, _0332_ });
  assign _0522_ = _0230_ ? _0521_ : _0520_;
  assign _0523_ = _0217_ ? reg_op1 : _0522_;
  function [31:0] _1179_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1179_ = b[31:0];
      2'b1?:
        _1179_ = b[63:32];
      default:
        _1179_ = a;
    endcase
  endfunction
  assign _0524_ = _1179_(cpuregs_rs1, { 32'hxxxxxxxx, _0601_ }, { is_rdcycle_rdcycleh_rdinstr_rdinstrh, is_lui_auipc_jal });
  assign _0089_ = resetn ? _0519_ : reg_op1;
  assign _0525_ = instr_jal ? _0116_ : _0114_;
  assign _0526_ = decoder_trigger ? _0525_ : _0103_;
  assign _0527_ = _0215_ ? _0526_ : reg_next_pc;
  assign _0088_ = resetn ? _0527_ : 32'h00000000;
  assign _0528_ = _0215_ ? _0103_ : reg_pc;
  assign _0092_ = resetn ? _0528_ : 32'h00000000;
  assign _0529_ = decoder_trigger ? _0115_ : count_instr;
  assign _0530_ = _0215_ ? _0529_ : count_instr;
  assign _0003_ = resetn ? _0530_ : 64'h0000000000000000;
  assign _0012_ = resetn ? eoi : 32'h00000000;
  assign _0087_ = resetn ? pcpi_valid : 1'h0;
  assign _0000_[31] = _0294_ ? 1'h1 : 1'h0;
  assign _0098_ = _0133_ ? 1'h1 : 1'h0;
  function [31:0] _1194_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1194_ = b[31:0];
      2'b1?:
        _1194_ = b[63:32];
      default:
        _1194_ = a;
    endcase
  endfunction
  assign cpuregs_wrdata = _1194_(32'hxxxxxxxx, { _0112_, _0599_ }, { latched_branch, _0292_ });
  assign cpuregs_write = _0215_ ? _0098_ : 1'h0;
  function [31:0] _1196_;
    input [31:0] a;
    input [223:0] b;
    input [6:0] s;
    casez (s) // synopsys parallel_case
      7'b??????1:
        _1196_ = b[31:0];
      7'b?????1?:
        _1196_ = b[63:32];
      7'b????1??:
        _1196_ = b[95:64];
      7'b???1???:
        _1196_ = b[127:96];
      7'b??1????:
        _1196_ = b[159:128];
      7'b?1?????:
        _1196_ = b[191:160];
      7'b1??????:
        _1196_ = b[223:192];
      default:
        _1196_ = a;
    endcase
  endfunction
  assign alu_out = _1196_(32'hxxxxxxxx, { alu_add_sub, 31'h00000000, alu_out_0, _0604_, _0443_, _0121_, alu_shl, alu_shr }, { is_lui_auipc_jal_jalr_addi_add_sub, is_compare, _0329_, _0330_, _0331_, _0290_, _0291_ });
  function [0:0] _1197_;
    input [0:0] a;
    input [5:0] b;
    input [5:0] s;
    casez (s) // synopsys parallel_case
      6'b?????1:
        _1197_ = b[0:0];
      6'b????1?:
        _1197_ = b[1:1];
      6'b???1??:
        _1197_ = b[2:2];
      6'b??1???:
        _1197_ = b[3:3];
      6'b?1????:
        _1197_ = b[4:4];
      6'b1?????:
        _1197_ = b[5:5];
      default:
        _1197_ = a;
    endcase
  endfunction
  assign alu_out_0 = _1197_(1'hx, { alu_eq, _0316_, _0317_, _0318_, alu_lts, alu_ltu }, { instr_beq, instr_bne, instr_bge, instr_bgeu, is_slti_blt_slt, is_sltiu_bltu_sltu });
  assign _0008_[4] = _0295_ ? mem_rdata_latched[19] : decoded_rs1[4];
  assign _0006_[10] = _0295_ ? mem_rdata_latched[30] : decoded_imm_j[10];
  assign _0006_[7] = _0295_ ? mem_rdata_latched[27] : decoded_imm_j[7];
  assign _0006_[6] = _0295_ ? mem_rdata_latched[26] : decoded_imm_j[6];
  assign _0006_[3:1] = _0295_ ? mem_rdata_latched[23:21] : decoded_imm_j[3:1];
  assign _0006_[5] = _0295_ ? mem_rdata_latched[25] : decoded_imm_j[5];
  assign _0006_[9:8] = _0295_ ? mem_rdata_latched[29:28] : decoded_imm_j[9:8];
  assign _0006_[31:20] = _0295_ ? { mem_rdata_latched[31], mem_rdata_latched[31], mem_rdata_latched[31], mem_rdata_latched[31], mem_rdata_latched[31], mem_rdata_latched[31], mem_rdata_latched[31], mem_rdata_latched[31], mem_rdata_latched[31], mem_rdata_latched[31], mem_rdata_latched[31], mem_rdata_latched[31] } : decoded_imm_j[31:20];
  assign _0006_[4] = _0295_ ? mem_rdata_latched[24] : decoded_imm_j[4];
  assign _0006_[11] = _0295_ ? mem_rdata_latched[20] : decoded_imm_j[11];
  assign _0006_[0] = _0295_ ? 1'h0 : decoded_imm_j[0];
  assign _0008_[3:0] = _0295_ ? mem_rdata_latched[18:15] : decoded_rs1[3:0];
  assign _0063_ = _0231_ ? 1'h0 : _0593_;
  assign _0056_ = _0295_ ? _0229_ : is_alu_reg_reg;
  assign _0055_ = _0295_ ? _0228_ : is_alu_reg_imm;
  assign _0531_ = _0295_ ? _0225_ : is_beq_bne_blt_bge_bltu_bgeu;
  assign _0057_ = resetn ? _0531_ : 1'h0;
  assign _0064_ = _0295_ ? _0227_ : is_sb_sh_sw;
  assign _0059_ = _0231_ ? _0327_ : is_jalr_addi_slti_sltiu_xori_ori_andi;
  assign _0065_ = _0231_ ? _0287_ : is_slli_srli_srai;
  assign _0060_ = _0295_ ? _0226_ : is_lb_lh_lw_lbu_lhu;
  assign _0001_ = _0295_ ? 1'h0 : compressed_instr;
  assign _0532_ = _0231_ ? 1'h0 : _0594_;
  assign _0058_ = resetn ? _0532_ : 1'h0;
  function [31:0] _1222_;
    input [31:0] a;
    input [159:0] b;
    input [4:0] s;
    casez (s) // synopsys parallel_case
      5'b????1:
        _1222_ = b[31:0];
      5'b???1?:
        _1222_ = b[63:32];
      5'b??1??:
        _1222_ = b[95:64];
      5'b?1???:
        _1222_ = b[127:96];
      5'b1????:
        _1222_ = b[159:128];
      default:
        _1222_ = a;
    endcase
  endfunction
  assign _0533_ = _1222_(32'b0000000000000000000000000000000x, { decoded_imm_j, mem_rdata_q[31:12], 12'h000, mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31:20], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[7], mem_rdata_q[30:25], mem_rdata_q[11:8], 1'h0, mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31], mem_rdata_q[31:25], mem_rdata_q[11:7] }, { instr_jal, _0535_, _0534_, is_beq_bne_blt_bge_bltu_bgeu, is_sb_sh_sw });
  assign _0005_ = _0231_ ? _0533_ : decoded_imm;
  assign _0009_ = _0295_ ? mem_rdata_latched[24:20] : decoded_rs2;
  assign _0006_[19:12] = _0295_ ? mem_rdata_latched[19:12] : decoded_imm_j[19:12];
  assign _0007_ = _0295_ ? mem_rdata_latched[11:7] : decoded_rd;
  assign _0039_ = _0295_ ? 1'h0 : instr_retirq;
  assign _0024_ = _0231_ ? _0283_ : instr_ecall_ebreak;
  assign _0038_ = _0231_ ? _0281_ : instr_rdinstrh;
  assign _0037_ = _0231_ ? _0280_ : instr_rdinstr;
  assign _0036_ = _0231_ ? _0279_ : instr_rdcycleh;
  assign _0035_ = _0231_ ? _0276_ : instr_rdcycle;
  assign _0536_ = _0231_ ? _0273_ : instr_and;
  assign _0015_ = resetn ? _0536_ : 1'h0;
  assign _0537_ = _0231_ ? _0271_ : instr_or;
  assign _0033_ = resetn ? _0537_ : 1'h0;
  assign _0538_ = _0231_ ? _0269_ : instr_sra;
  assign _0048_ = resetn ? _0538_ : 1'h0;
  assign _0539_ = _0231_ ? _0268_ : instr_srl;
  assign _0050_ = resetn ? _0539_ : 1'h0;
  assign _0540_ = _0231_ ? _0266_ : instr_xor;
  assign _0053_ = resetn ? _0540_ : 1'h0;
  assign _0541_ = _0231_ ? _0264_ : instr_sltu;
  assign _0047_ = resetn ? _0541_ : 1'h0;
  assign _0542_ = _0231_ ? _0262_ : instr_slt;
  assign _0044_ = resetn ? _0542_ : 1'h0;
  assign _0543_ = _0231_ ? _0260_ : instr_sll;
  assign _0042_ = resetn ? _0543_ : 1'h0;
  assign _0544_ = _0231_ ? _0258_ : instr_sub;
  assign _0052_ = resetn ? _0544_ : 1'h0;
  assign _0545_ = _0231_ ? _0257_ : instr_add;
  assign _0013_ = resetn ? _0545_ : 1'h0;
  assign _0049_ = _0231_ ? _0255_ : instr_srai;
  assign _0051_ = _0231_ ? _0254_ : instr_srli;
  assign _0043_ = _0231_ ? _0252_ : instr_slli;
  assign _0546_ = _0231_ ? _0250_ : instr_andi;
  assign _0016_ = resetn ? _0546_ : 1'h0;
  assign _0547_ = _0231_ ? _0249_ : instr_ori;
  assign _0034_ = resetn ? _0547_ : 1'h0;
  assign _0548_ = _0231_ ? _0248_ : instr_xori;
  assign _0054_ = resetn ? _0548_ : 1'h0;
  assign _0549_ = _0231_ ? _0247_ : instr_sltiu;
  assign _0046_ = resetn ? _0549_ : 1'h0;
  assign _0550_ = _0231_ ? _0246_ : instr_slti;
  assign _0045_ = resetn ? _0550_ : 1'h0;
  assign _0551_ = _0231_ ? _0245_ : instr_addi;
  assign _0014_ = resetn ? _0551_ : 1'h0;
  assign _0041_ = _0231_ ? _0244_ : instr_sh;
  assign _0040_ = _0231_ ? _0243_ : instr_sb;
  assign _0030_ = _0231_ ? _0242_ : instr_lhu;
  assign _0028_ = _0231_ ? _0241_ : instr_lbu;
  assign _0032_ = _0231_ ? _0240_ : instr_lw;
  assign _0029_ = _0231_ ? _0239_ : instr_lh;
  assign _0027_ = _0231_ ? _0238_ : instr_lb;
  assign _0552_ = _0231_ ? _0237_ : instr_bgeu;
  assign _0020_ = resetn ? _0552_ : 1'h0;
  assign _0553_ = _0231_ ? _0236_ : instr_bltu;
  assign _0022_ = resetn ? _0553_ : 1'h0;
  assign _0554_ = _0231_ ? _0235_ : instr_bge;
  assign _0019_ = resetn ? _0554_ : 1'h0;
  assign _0555_ = _0231_ ? _0234_ : instr_blt;
  assign _0021_ = resetn ? _0555_ : 1'h0;
  assign _0556_ = _0231_ ? _0233_ : instr_bne;
  assign _0023_ = resetn ? _0556_ : 1'h0;
  assign _0557_ = _0231_ ? _0232_ : instr_beq;
  assign _0018_ = resetn ? _0557_ : 1'h0;
  assign _0026_ = _0295_ ? _0312_ : instr_jalr;
  assign _0025_ = _0295_ ? _0222_ : instr_jal;
  assign _0017_ = _0295_ ? _0221_ : instr_auipc;
  assign _0031_ = _0295_ ? _0220_ : instr_lui;
  assign _0558_ = mem_do_rinst ? 2'h0 : mem_state;
  function [1:0] _1292_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _1292_ = b[1:0];
      4'b??1?:
        _1292_ = b[3:2];
      4'b?1??:
        _1292_ = b[5:4];
      4'b1???:
        _1292_ = b[7:6];
      default:
        _1292_ = a;
    endcase
  endfunction
  assign _0559_ = _1292_(mem_state, { _0567_, _0564_, _0561_, _0558_ }, { _0310_, _0565_, _0562_, _0560_ });
  assign _0560_ = mem_state == 2'h3;
  assign _0561_ = mem_xfer ? 2'h0 : mem_state;
  assign _0562_ = mem_state == 2'h2;
  assign _0564_ = mem_xfer ? _0563_ : mem_state;
  assign _0565_ = mem_state == 1'h1;
  assign _0566_ = _0343_ ? 2'h1 : mem_state;
  assign _0567_ = mem_do_wdata ? 2'h2 : _0566_;
  assign _0568_ = resetn ? mem_state : 2'h0;
  assign _0082_ = _0344_ ? _0568_ : _0559_;
  assign _0569_ = _0346_ ? _0123_ : mem_wstrb;
  assign _0570_ = _0343_ ? 4'h0 : _0569_;
  assign _0571_ = _0310_ ? _0570_ : _0569_;
  assign _0086_ = _0344_ ? mem_wstrb : _0571_;
  assign _0572_ = mem_la_write ? mem_la_wdata : mem_wdata;
  assign _0084_ = _0344_ ? mem_wdata : _0572_;
  assign _0573_ = _0346_ ? mem_la_addr : mem_addr;
  assign _0075_ = _0344_ ? mem_addr : _0573_;
  assign _0574_ = _0343_ ? _0342_ : mem_instr;
  assign _0575_ = mem_do_wdata ? 1'h0 : _0574_;
  assign _0576_ = _0310_ ? _0575_ : mem_instr;
  assign _0080_ = _0344_ ? mem_instr : _0576_;
  assign _0577_ = mem_xfer ? 1'h0 : mem_valid;
  function [0:0] _1315_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1315_ = b[0:0];
      2'b1?:
        _1315_ = b[1:1];
      default:
        _1315_ = a;
    endcase
  endfunction
  assign _0578_ = _1315_(mem_valid, { _0580_, _0577_ }, { _0310_, _0134_ });
  assign _0579_ = _0343_ ? 1'h1 : mem_valid;
  assign _0580_ = mem_do_wdata ? 1'h1 : _0579_;
  assign _0581_ = _0345_ ? 1'h0 : mem_valid;
  assign _0083_ = _0344_ ? _0581_ : _0578_;
  assign _0081_[31] = mem_xfer ? mem_rdata[31] : mem_rdata_q[31];
  assign _0081_[7] = mem_xfer ? mem_rdata[7] : mem_rdata_q[7];
  assign _0081_[24:20] = mem_xfer ? mem_rdata[24:20] : mem_rdata_q[24:20];
  assign _0081_[19:15] = mem_xfer ? mem_rdata[19:15] : mem_rdata_q[19:15];
  assign _0081_[6:0] = mem_xfer ? mem_rdata[6:0] : mem_rdata_q[6:0];
  assign _0081_[14:12] = mem_xfer ? mem_rdata[14:12] : mem_rdata_q[14:12];
  assign _0081_[11:8] = mem_xfer ? mem_rdata[11:8] : mem_rdata_q[11:8];
  assign _0081_[30:25] = mem_xfer ? mem_rdata[30:25] : mem_rdata_q[30:25];
  function [7:0] _1328_;
    input [7:0] a;
    input [31:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _1328_ = b[7:0];
      4'b??1?:
        _1328_ = b[15:8];
      4'b?1??:
        _1328_ = b[23:16];
      4'b1???:
        _1328_ = b[31:24];
      default:
        _1328_ = a;
    endcase
  endfunction
  assign _0104_ = _1328_(8'hxx, { mem_rdata[7:0], mem_rdata[15:8], mem_rdata[23:16], mem_rdata[31:24] }, { _0585_, _0584_, _0583_, _0582_ });
  assign _0582_ = reg_op1[1:0] == 2'h3;
  assign _0583_ = reg_op1[1:0] == 2'h2;
  assign _0584_ = reg_op1[1:0] == 1'h1;
  assign _0585_ = ! reg_op1[1:0];
  function [15:0] _1333_;
    input [15:0] a;
    input [31:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1333_ = b[15:0];
      2'b1?:
        _1333_ = b[31:16];
      default:
        _1333_ = a;
    endcase
  endfunction
  assign _0099_ = _1333_(16'hxxxx, { mem_rdata[15:0], mem_rdata[31:16] }, { _0586_, reg_op1[1] });
  assign _0586_ = ~ reg_op1[1];
  function [31:0] _1335_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1335_ = b[31:0];
      2'b1?:
        _1335_ = b[63:32];
      default:
        _1335_ = a;
    endcase
  endfunction
  assign mem_rdata_word = _1335_({ 24'h000000, _0104_ }, { mem_rdata, 16'h0000, _0099_ }, { _0218_, _0219_ });
  function [3:0] _1336_;
    input [3:0] a;
    input [7:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1336_ = b[3:0];
      2'b1?:
        _1336_ = b[7:4];
      default:
        _1336_ = a;
    endcase
  endfunction
  assign mem_la_wstrb = _1336_(_0595_, { 4'hf, _0603_ }, { _0218_, _0219_ });
  function [31:0] _1337_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _1337_ = b[31:0];
      2'b1?:
        _1337_ = b[63:32];
      default:
        _1337_ = a;
    endcase
  endfunction
  assign mem_la_wdata = _1337_({ reg_op2[7:0], reg_op2[7:0], reg_op2[7:0], reg_op2[7:0] }, { reg_op2, reg_op2[15:0], reg_op2[15:0] }, { _0218_, _0219_ });
  assign _0108_ = mem_do_rdata ? 1'h0 : 1'h1;
  assign _0105_ = _0334_ ? _0108_ : 1'h0;
  assign _0107_ = _0334_ ? _0109_ : 1'h0;
  assign _0106_ = is_beq_bne_blt_bge_bltu_bgeu ? _0110_ : 1'h0;
  assign _0109_ = mem_do_wdata ? 1'h0 : 1'h1;
  assign _0110_ = alu_out_0 ? 1'h1 : 1'h0;
  assign _0587_ = & { mem_state[0], mem_state[1] };
  assign _0588_ = | decoded_rs;
  assign _0589_ = | { _0286_, _0285_, _0284_ };
  assign _0590_ = | { _0198_, _0200_, _0202_, _0203_, _0204_, _0205_ };
  assign _0535_ = | { instr_lui, instr_auipc };
  assign _0534_ = | { instr_jalr, is_lb_lh_lw_lbu_lhu, is_alu_reg_imm };
  assign _0591_ = | { reg_pc[0], reg_pc[1] };
  assign _0592_ = | { mem_state[0], mem_state[1] };
  assign is_rdcycle_rdcycleh_rdinstr_rdinstrh = | { instr_rdcycle, instr_rdcycleh, instr_rdinstr, instr_rdinstrh };
  assign _0062_ = | { instr_lui, instr_auipc, instr_jal };
  assign _0593_ = | { instr_lui, instr_auipc, instr_jal, instr_jalr, instr_addi, instr_add, instr_sub };
  assign _0066_ = | { instr_blt, instr_slti, instr_slt };
  assign _0067_ = | { instr_bltu, instr_sltiu, instr_sltu };
  assign _0061_ = | { instr_lw, instr_lbu, instr_lhu };
  assign _0594_ = | { instr_slti, instr_sltiu, instr_slt, instr_sltu, is_beq_bne_blt_bge_bltu_bgeu };
  assign alu_shl = reg_op1 << reg_op2[4:0];
  assign _0595_ = 1'h1 << reg_op1[1:0];
  assign alu_shr = $signed({ _0598_, reg_op1 }) >>> reg_op2[4:0];
  assign _0596_ = reg_op1 - reg_op2;
  assign _0195_[4:0] = reg_sh - 3'h4;
  assign _0597_[4:0] = reg_sh - 1'h1;
  assign next_pc = _0289_ ? _0120_ : reg_next_pc;
  assign alu_add_sub = instr_sub ? _0596_ : _0111_;
  assign _0598_ = _0328_ ? reg_op1[31] : 1'h0;
  assign _0196_[2:0] = latched_compr ? 3'h2 : 3'h4;
  assign _0599_ = latched_stalu ? alu_out_q : reg_out;
  assign decoded_rs = _0216_ ? decoded_rs2 : decoded_rs1;
  assign cpuregs_rs1 = _0588_ ? _0441_ : 32'h00000000;
  assign _0002_ = resetn ? _0113_ : 64'h0000000000000000;
  assign _0600_ = latched_store ? _0122_ : reg_next_pc;
  assign _0197_[2:0] = compressed_instr ? 3'h2 : 3'h4;
  assign _0601_ = instr_lui ? 32'h00000000 : reg_pc;
  assign _0602_ = is_slli_srli_srai ? { 27'h0000000, decoded_rs2 } : decoded_imm;
  assign mem_la_addr = _0342_ ? { _0119_, 2'h0 } : { reg_op1[31:2], 2'h0 };
  assign mem_rdata_latched = mem_xfer ? mem_rdata : mem_rdata_q;
  assign _0603_ = reg_op1[1] ? 4'hc : 4'h3;
  assign _0563_ = _0339_ ? 2'h0 : 2'h3;
  assign _0604_ = reg_op1 ^ reg_op2;
  assign cpuregs_rs2 = cpuregs_rs1;
  assign dbg_mem_addr = mem_addr;
  assign dbg_mem_instr = mem_instr;
  assign dbg_mem_rdata = mem_rdata;
  assign dbg_mem_ready = mem_ready;
  assign dbg_mem_valid = mem_valid;
  assign dbg_mem_wdata = mem_wdata;
  assign dbg_mem_wstrb = mem_wstrb;
  assign do_waitirq = trace_valid;
  assign mem_rdata_latched_noshuffle = mem_rdata_latched;
  assign pcpi_insn = 32'hxxxxxxxx;
  assign pcpi_rs1 = reg_op1;
  assign pcpi_rs2 = reg_op2;
endmodule
