/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 9.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "naive.v:1" *)
module naive(clk, in, out);
  (* src = "naive.v:3" *)
  input clk;
  (* src = "naive.v:2" *)
  input in;
  (* src = "naive.v:4" *)
  output out;
  reg out;
  always @(posedge clk)
      out <= in;
endmodule
