two_reg: 
	./build/func_extract ../../func_test/two_reg/two_reg_yosys.v.clean ../../func_test/two_reg/two_reg_as.txt 0

word:
	./build/func_extract ../../func_test/word_adder 0#make sure design.v is cleaned with taint_gen!

word1:
	./build/func_extract ../../func_test/word_adder 1

pid:
	./build/func_extract ../../func_test/PID 1

pidc:
	./build/func_extract ../../func_test/PID 0#make sure design.v is cleaned with taint_gen!

tmp:
	#./build/func_extract ../../func_test/tmp/tmp.v ../../func_test/tmp/as.txt 1
	./build/func_extract ../../func_test/tmp/tmp.v 0

ad:
	./build/func_extract ../../func_test/advanced 0#make sure design.v is cleaned with taint_gen!

ad1:
	./build/func_extract ../../func_test/advanced 1

ex:
	./build/func_extract ../../func_test/expand_key 0#make sure design.v is cleaned with taint_gen!

ex1:
	./build/func_extract ../../func_test/expand_key 1

s:
	./build/func_extract ../../func_test/aes_s 0#make sure design.v is cleaned with taint_gen!

s1:
	./build/func_extract ../../func_test/aes_s 1

s4:
	./build/func_extract ../../func_test/aes_s4 0

s41:
	./build/func_extract ../../func_test/aes_s4 1

ss:
	./build/func_extract ../../func_test/aes_short_s 0#make sure design.v is cleaned with taint_gen!

ss1:
	./build/func_extract ../../func_test/aes_short_s 1

1281:
	./build/func_extract ../../func_test/aes_128_hier 1

128:
	./build/func_extract ../../func_test/aes_128_hier 0

aes1:
	./build/func_extract ../../func_test/aes_fifo 1

aes:
	./build/func_extract ../../func_test/aes_fifo 0

aes2:
	./build/func_extract ../../func_test/aes_fifo_v2 0


aestop1:
	./build/func_extract ../../func_test/aes 1

aestop:
	./build/func_extract ../../func_test/aes 0

aestopr:
	./build/func_extract ../../func_test/aes 0 -reg

case1:
	./build/func_extract ../../func_test/case_test 1

case:
	./build/func_extract ../../func_test/case_test 0


wmo:
	./build/func_extract ../../func_test/word_adder_modular_old 0

wm:
	./build/func_extract ../../func_test/word_adder_modular 0

wm1:
	./build/func_extract ../../func_test/word_adder_modular 1


nondet:
	./build/func_extract ../../func_test/nondetermined_bound 0

nondet1:
	./build/func_extract ../../func_test/nondetermined_bound 1


or:
	./build/func_extract ../../func_test/one_round 0

or1:
	./build/func_extract ../../func_test/one_round 1

acc1:
	./build/func_extract ../../func_test/accum 1

acc:
	./build/func_extract ../../func_test/accum 0


riscv1:
	./build/func_extract ../../func_test/riscv 1

riscv:
	./build/func_extract ../../func_test/riscv 0

riscvr:
	./build/func_extract ../../func_test/riscv 0 -reg


rvfifo1:
	./build/func_extract ../../func_test/riscv_fifo 1

rvfifo:
	./build/func_extract ../../func_test/riscv_fifo 0


bi1:
	./build/func_extract ../../func_test/biriscv 1

bi:
	./build/func_extract ../../func_test/biriscv 0

urv1:
	./build/func_extract ../../func_test/ultra_riscv 1

urv:
	./build/func_extract ../../func_test/ultra_riscv 0


urvff1:
	./build/func_extract ../../func_test/ultra_riscv_fifo 1

urvff:
	./build/func_extract ../../func_test/ultra_riscv_fifo 0


naive:
	./build/func_extract ../../func_test/naive 0


sha1:
	./build/func_extract ../../func_test/SHA 1

sha:
	./build/func_extract ../../func_test/SHA 0

shar:
	./build/func_extract ../../func_test/SHA 0 -reg


gb1:
	./build/func_extract ../../func_test/gb 1

gb:
	./build/func_extract ../../func_test/gb 0

gbr:
	./build/func_extract ../../func_test/gb 0 -reg


rbm1:
	./build/func_extract ../../func_test/rbm 1

rbm:
	./build/func_extract ../../func_test/rbm 0

rbmr:
	./build/func_extract ../../func_test/rbm 0 -reg


80511:
	./build/func_extract ../../func_test/8051 1

8051:
	./build/func_extract ../../func_test/8051 0

8051r:
	./build/func_extract ../../func_test/8051 0 -reg

adder:
	./build/func_extract ../../func_test/adder 0

vec1:
	./build/func_extract ../../func_test/vecAdd 1

vec:
	./build/func_extract ../../func_test/vecAdd 0

vecb1:
	./build/func_extract ../../func_test/vecAddBuffer 1

vecb:
	./build/func_extract ../../func_test/vecAddBuffer 0

vecf1:
	./build/func_extract ../../func_test/vecAddBufferFlat 1

vecf:
	./build/func_extract ../../func_test/vecAddBufferFlat 0

vta1:
	./build/func_extract ../../func_test/vta 1

vta:
	./build/func_extract ../../func_test/vta 0


vtahier1:
	./build/func_extract ../../func_test/vta_hier 1

vtahier:
	./build/func_extract ../../func_test/vta_hier 0


buf1:
	./build/func_extract ../../func_test/buffer_test 1  

buf:
	./build/func_extract ../../func_test/buffer_test 0


3d1:
	./build/func_extract ../../func_test/threeDloop 1

3d:
	./build/func_extract ../../func_test/threeDloop 0

