two_reg: 
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/two_reg/two_reg_yosys.v.clean /workspace/research/ILA/autoGenILA/src/func_extract/test/two_reg/two_reg_as.txt 0

word:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/word_adder 0#make sure design.v is cleaned with taint_gen!

pid:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/PID 1

pidc:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/PID 0#make sure design.v is cleaned with taint_gen!

tmp:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/tmp/tmp.v /workspace/research/ILA/autoGenILA/src/func_extract/test/tmp/as.txt 1

ad:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/advanced 0#make sure design.v is cleaned with taint_gen!

ad1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/advanced 1

ex:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/expand_key 0#make sure design.v is cleaned with taint_gen!

ex1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/expand_key 1

s:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_s 0#make sure design.v is cleaned with taint_gen!

s1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_s 1

ss:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_short_s 0#make sure design.v is cleaned with taint_gen!

ss1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_short_s 1

aes1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes 1

aes:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes 0

case1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/case_test 1

case:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/case_test 0

wm:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/word_adder_modular 0

wm1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/word_adder_modular 1
