two_reg: 
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/two_reg/two_reg_yosys.v.clean /workspace/research/ILA/autoGenILA/src/func_extract/test/two_reg/two_reg_as.txt 0

word:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/word_adder 0#make sure design.v is cleaned with taint_gen!

pid:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/PID 1

pidc:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/PID 0#make sure design.v is cleaned with taint_gen!

tmp:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/tmp/tmp.v /workspace/research/ILA/autoGenILA/src/func_extract/test/tmp/as.txt 1

ad:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/advanced 0#make sure design.v is cleaned with taint_gen!

ad1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/advanced 1

ex:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/expand_key 0#make sure design.v is cleaned with taint_gen!

ex1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/expand_key 1

s:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_s 0#make sure design.v is cleaned with taint_gen!

s1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_s 1

s4:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_s4 0

s41:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_s4 1

ss:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_short_s 0#make sure design.v is cleaned with taint_gen!

ss1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_short_s 1

1281:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_128 1

128:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_128 0

aes1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_fifo 1

aes:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_fifo 0

aestop1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes 1

aestop:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes 0

aestopr:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes 0 -reg

case1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/case_test 1

case:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/case_test 0


wmo:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/word_adder_modular_old 0

wm:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/word_adder_modular 0

wm1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/word_adder_modular 1


nondet:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/nondetermined_bound 0

nondet1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/nondetermined_bound 1


or:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/one_round 0

or1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/one_round 1

acc1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/accum 1

acc:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/accum 0


riscv1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/riscv 1

riscv:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/riscv 0

riscvr:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/riscv 0 -reg


bi1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/biriscv 1

bi:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/biriscv 0

urv1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/ultra_riscv 1

urv:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/ultra_riscv 0

naive:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/naive 0


sha1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/SHA 1

sha:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/SHA 0

shar:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/SHA 0 -reg


gb1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/gb 1

gb:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/gb 0

gbr:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/gb 0 -reg


rbm1:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/rbm 1

rbm:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/rbm 0

rbmr:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/rbm 0 -reg


80511:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/8051 1

8051:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/8051 0

8051r:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/8051 0 -reg

adder:
	./build/func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/adder 0
