two_reg: 
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/two_reg/two_reg_yosys.v.clean /workspace/research/ILA/autoGenILA/src/func_extract/test/two_reg/two_reg_as.txt 0

word:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/word_adder/word_adder_yosys.v.clean /workspace/research/ILA/autoGenILA/src/func_extract/test/word_adder/instr.txt 0

aes:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/PID/PID_flatten.v /workspace/research/ILA/autoGenILA/src/func_extract/test/PID/instr.txt 1

aesc:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/PID/PID_flatten.v.clean /workspace/research/ILA/autoGenILA/src/func_extract/test/PID/instr.txt 0

