two_reg: 
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/two_reg/two_reg_yosys.v.clean /workspace/research/ILA/autoGenILA/src/func_extract/test/two_reg/two_reg_as.txt 0

word:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/word_adder 0

pid:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/PID 1

pidc:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/PID 0

tmp:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/tmp/tmp.v /workspace/research/ILA/autoGenILA/src/func_extract/test/tmp/as.txt 1

ad:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/advanced 0

ad1:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/advanced 1

ex:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/expand_key 0

ex1:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/expand_key 1

s:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_s 0

s1:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_s 1

ss:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_short_s 0

ss1:
	../func_extract /workspace/research/ILA/autoGenILA/src/func_extract/test/aes_short_s 1
