clean:
	rm added_work_set.txt
	rm all_regs.txt 
	rm asv_info.txt
	rm design.v.nocomment
	rm func_info.txt
	rm goal.txt
	rm link.sh
	rm reg_values.txt
	rm result.txt
	rm simplify_time.txt
	rm up_gen_time.txt
