/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 9.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "two_reg.v:6" *)
module two_reg(clk, rst, func, out_wire, sign);
  (* src = "two_reg.v:27" *)
  wire _0_;
  (* src = "two_reg.v:24" *)
  wire _1_;
  (* src = "two_reg.v:7" *)
  input clk;
  (* src = "two_reg.v:9" *)
  input [1:0] func;
  (* src = "two_reg.v:14" *)
  wire out;
  (* src = "two_reg.v:10" *)
  output out_wire;
  (* src = "two_reg.v:8" *)
  input rst;
  (* src = "two_reg.v:11" *)
  output sign;
  reg sign;
  (* src = "two_reg.v:23" *)
  wire sign_next;
  assign _1_ = func == (* src = "two_reg.v:24" *) 2'h2;
  always @(posedge clk)
      sign <= _0_;
  assign _0_ = rst ? (* src = "two_reg.v:28" *) 1'h0 : sign_next;
  assign sign_next = _1_ ? (* src = "two_reg.v:24" *) 1'h1 : sign;
  (* src = "two_reg.v:16" *)
  sub sub0 (
    .clk(clk),
    .func(func),
    .out(out),
    .rst(rst)
  );
  assign out_wire = out;
endmodule

(* src = "two_reg.v:37" *)
module sub(clk, rst, func, out);
  (* src = "two_reg.v:51" *)
  wire _00_;
  (* src = "two_reg.v:51" *)
  wire _01_;
  (* src = "two_reg.v:48" *)
  wire _02_;
  (* src = "two_reg.v:49" *)
  wire _03_;
  (* src = "two_reg.v:49" *)
  wire _04_;
  (* src = "two_reg.v:38" *)
  input clk;
  (* src = "two_reg.v:44" *)
  reg enable;
  (* src = "two_reg.v:45" *)
  wire enable_next;
  (* src = "two_reg.v:40" *)
  input [1:0] func;
  (* src = "two_reg.v:41" *)
  output out;
  reg out;
  (* src = "two_reg.v:46" *)
  wire out_next;
  (* src = "two_reg.v:39" *)
  input rst;
  assign _02_ = func == (* src = "two_reg.v:48" *) 1'h1;
  assign _03_ = func == (* src = "two_reg.v:49" *) 2'h2;
  assign _04_ = _03_ && (* src = "two_reg.v:49" *) enable;
  always @(posedge clk)
      out <= _01_;
  always @(posedge clk)
      enable <= _00_;
  assign _00_ = rst ? (* src = "two_reg.v:52" *) 1'h0 : enable_next;
  assign _01_ = rst ? (* src = "two_reg.v:52" *) 1'h0 : out_next;
  assign enable_next = _02_ ? (* src = "two_reg.v:48" *) 1'h1 : enable;
  assign out_next = _04_ ? (* src = "two_reg.v:49" *) 1'h1 : out;
endmodule

