/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 9.0.0 -fPIC -Os) */

(* src = "nondet.v:1" *)
module add(in1, in2, out);
  (* src = "nondet.v:2" *)
  input [1:0] in1;
  (* src = "nondet.v:3" *)
  input [1:0] in2;
  (* src = "nondet.v:4" *)
  output [1:0] out;
  assign out = in1 + (* src = "nondet.v:5" *) in2;
endmodule

(* top =  1  *)
(* src = "nondet.v:8" *)
module top(clk, rst, func, inCount, result);
  (* src = "nondet.v:31" *)
  wire [1:0] _00_;
  (* src = "nondet.v:31" *)
  wire _01_;
  (* src = "nondet.v:31" *)
  wire [1:0] _02_;
  (* src = "nondet.v:20" *)
  wire [31:0] _03_;
  (* src = "nondet.v:22" *)
  wire [31:0] _04_;
  (* src = "nondet.v:20" *)
  wire _05_;
  (* src = "nondet.v:21" *)
  wire _06_;
  (* src = "nondet.v:20" *)
  wire _07_;
  (* src = "nondet.v:20" *)
  wire _08_;
  (* src = "nondet.v:20" *)
  wire _09_;
  (* src = "nondet.v:22" *)
  wire [31:0] _10_;
  (* src = "nondet.v:9" *)
  input clk;
  (* src = "nondet.v:15" *)
  reg [1:0] counter;
  (* src = "nondet.v:21" *)
  wire [1:0] counter_next;
  (* src = "nondet.v:11" *)
  input [1:0] func;
  (* src = "nondet.v:12" *)
  input [1:0] inCount;
  (* src = "nondet.v:13" *)
  output [1:0] result;
  (* src = "nondet.v:10" *)
  input rst;
  (* src = "nondet.v:17" *)
  reg running;
  (* src = "nondet.v:20" *)
  wire running_next;
  (* src = "nondet.v:18" *)
  wire [1:0] sum;
  (* src = "nondet.v:16" *)
  reg [1:0] word_sum;
  (* src = "nondet.v:23" *)
  wire [1:0] word_sum_next;
  assign _05_ = func == (* src = "nondet.v:20" *) 2'h2;
  assign _06_ = func == (* src = "nondet.v:21" *) 1'h1;
  assign _07_ = counter > (* src = "nondet.v:20" *) 1'h0;
  assign _08_ = counter > (* src = "nondet.v:20" *) 1'h1;
  assign _09_ = _05_ && (* src = "nondet.v:20" *) _07_;
  assign _03_[0] = running && (* src = "nondet.v:20" *) _08_;
  always @(posedge clk)
      counter <= _00_;
  always @(posedge clk)
      word_sum <= _02_;
  always @(posedge clk)
      running <= _01_;
  assign _01_ = rst ? (* src = "nondet.v:32" *) 1'h0 : running_next;
  assign _02_ = rst ? (* src = "nondet.v:32" *) 2'h0 : word_sum_next;
  assign _00_ = rst ? (* src = "nondet.v:32" *) 2'h0 : counter_next;
  assign _04_[1:0] = counter - (* src = "nondet.v:22" *) 1'h1;
  assign running_next = _09_ ? (* src = "nondet.v:20" *) 1'h1 : _03_[0];
  assign _10_[1:0] = running ? (* src = "nondet.v:22" *) _04_[1:0] : counter;
  assign counter_next = _06_ ? (* src = "nondet.v:22" *) inCount : _10_[1:0];
  assign word_sum_next = running ? (* src = "nondet.v:23" *) sum : word_sum;
  (* src = "nondet.v:25" *)
  add u0 (
    .in1(word_sum),
    .in2(2'h1),
    .out(sum)
  );
  assign result = word_sum;
endmodule
