/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 9.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "word_adder_clean.v:9" *)
module word_adder(clk, rst, func, inWord, result);
  (* src = "word_adder_clean.v:38" *)
  wire [4:0] _00_;
  wire _01_;
  (* src = "word_adder_clean.v:38" *)
  wire [8:0] _02_;
  (* src = "word_adder_clean.v:31" *)
  wire [8:0] _03_;
  (* src = "word_adder_clean.v:27" *)
  wire [31:0] _04_;
  (* src = "word_adder_clean.v:23" *)
  wire _05_;
  (* src = "word_adder_clean.v:26" *)
  wire _06_;
  (* src = "word_adder_clean.v:23" *)
  wire _07_;
  (* src = "word_adder_clean.v:23" *)
  wire _08_;
  (* src = "word_adder_clean.v:23" *)
  wire _09_;
  (* src = "word_adder_clean.v:31" *)
  wire _10_;
  (* src = "word_adder_clean.v:27" *)
  wire [31:0] _11_;
  (* src = "word_adder_clean.v:10" *)
  input clk;
  (* src = "word_adder_clean.v:18" *)
  reg [4:0] counter;
  (* src = "word_adder_clean.v:26" *)
  wire [4:0] counter_next;
  (* src = "word_adder_clean.v:11" *)
  input [1:0] func;
  (* src = "word_adder_clean.v:12" *)
  input [8:0] inWord;
  (* src = "word_adder_clean.v:13" *)
  output [8:0] result;
  (* src = "word_adder_clean.v:10" *)
  input rst;
  (* src = "word_adder_clean.v:20" *)
  wire running;
  (* src = "word_adder_clean.v:16" *)
  reg [8:0] word;
  wire word_next;
  (* src = "word_adder_clean.v:17" *)
  reg [8:0] word_sum;
  (* src = "word_adder_clean.v:31" *)
  wire [8:0] word_sum_next;
  assign _03_ = word_sum + (* src = "word_adder_clean.v:31" *) _10_;
  assign _05_ = func == (* src = "word_adder_clean.v:23" *) 1'h1;
  assign _06_ = func == (* src = "word_adder_clean.v:26" *) 2'h2;
  assign running = counter > (* src = "word_adder_clean.v:20" *) 1'h0;
  assign _07_ = _05_ && (* src = "word_adder_clean.v:23" *) inWord;
  assign _08_ = _09_ && (* src = "word_adder_clean.v:23" *) word;
  assign _09_ = ! (* src = "word_adder_clean.v:23" *) _05_;
  assign word_next = _07_ || (* src = "word_adder_clean.v:23" *) _08_;
  always @(posedge clk)
      word <= { 8'h00, _01_ };
  always @(posedge clk)
      word_sum <= _02_;
  always @(posedge clk)
      counter <= _00_;
  assign _00_ = rst ? (* src = "word_adder_clean.v:39" *) 5'h00 : counter_next;
  assign _02_ = rst ? (* src = "word_adder_clean.v:39" *) 9'h000 : word_sum_next;
  assign _01_ = rst ? (* src = "word_adder_clean.v:39" *) 1'h0 : word_next;
  assign _10_ = word[$signed(_11_) +: 1];
  assign _11_ = counter - (* src = "word_adder_clean.v:27" *) 1'h1;
  assign _04_[4:0] = running ? (* src = "word_adder_clean.v:27" *) _11_[4:0] : 5'h00;
  assign counter_next = _06_ ? (* src = "word_adder_clean.v:27" *) 5'h08 : _04_[4:0];
  assign word_sum_next = running ? (* src = "word_adder_clean.v:31" *) _03_ : word_sum;
  assign result = word_sum;
endmodule
