/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 9.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "word_adder_yosys.v.clean.tainted.final:1" *)
module word_adder(clk, func, inWord, rstn, func_t, inWord_t, rstn_t, counter_r, result, word_r, word_sum_r);
  (* src = "word_adder_yosys.v.clean.tainted.final:368" *)
  wire _12_;
  (* src = "word_adder_yosys.v.clean.tainted.final:366" *)
  wire _13_;
  (* src = "word_adder_yosys.v.clean.tainted.final:352" *)
  wire _14_;
  (* src = "word_adder_yosys.v.clean.tainted.final:360" *)
  wire _15_;
  (* src = "word_adder_yosys.v.clean.tainted.final:358" *)
  wire _16_;
  (* src = "word_adder_yosys.v.clean.tainted.final:350" *)
  wire _17_;
  (* src = "word_adder_yosys.v.clean.tainted.final:353" *)
  wire [31:0] _18_;
  (* src = "word_adder_yosys.v.clean.tainted.final:361" *)
  wire [31:0] _19_;
  (* src = "word_adder_yosys.v.clean.tainted.final:369" *)
  wire [31:0] _20_;
  (* src = "word_adder_yosys.v.clean.tainted.final:378" *)
  wire _21_;
  (* src = "word_adder_yosys.v.clean.tainted.final:393" *)
  wire _22_;
  (* src = "word_adder_yosys.v.clean.tainted.final:408" *)
  wire _23_;
  (* src = "word_adder_yosys.v.clean.tainted.final:468" *)
  wire _24_;
  (* src = "word_adder_yosys.v.clean.tainted.final:483" *)
  wire _25_;
  (* src = "word_adder_yosys.v.clean.tainted.final:505" *)
  wire _26_;
  (* src = "word_adder_yosys.v.clean.tainted.final:2" *)
  wire [4:0] _00_;
  (* src = "word_adder_yosys.v.clean.tainted.final:4" *)
  wire _00__r;
  (* src = "word_adder_yosys.v.clean.tainted.final:3" *)
  wire _00__t;
  (* src = "word_adder_yosys.v.clean.tainted.final:11" *)
  wire _01_;
  (* src = "word_adder_yosys.v.clean.tainted.final:13" *)
  wire _01__r;
  (* src = "word_adder_yosys.v.clean.tainted.final:12" *)
  wire _01__t;
  (* src = "word_adder_yosys.v.clean.tainted.final:20" *)
  wire [8:0] _02_;
  (* src = "word_adder_yosys.v.clean.tainted.final:22" *)
  wire _02__r;
  (* src = "word_adder_yosys.v.clean.tainted.final:21" *)
  wire _02__t;
  (* src = "word_adder_yosys.v.clean.tainted.final:29" *)
  wire [8:0] _03_;
  (* src = "word_adder_yosys.v.clean.tainted.final:491" *)
  wire _03__c0;
  (* src = "word_adder_yosys.v.clean.tainted.final:495" *)
  wire _03__j10;
  (* src = "word_adder_yosys.v.clean.tainted.final:30" *)
  wire _03__t;
  wire [4:0] _04_;
  (* src = "word_adder_yosys.v.clean.tainted.final:476" *)
  wire _04__4_0_c0;
  (* src = "word_adder_yosys.v.clean.tainted.final:481" *)
  wire _04__4_0_j20;
  (* src = "word_adder_yosys.v.clean.tainted.final:468" *)
  wire _04__4_0_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:47" *)
  wire _05_;
  (* src = "word_adder_yosys.v.clean.tainted.final:245" *)
  wire _05__j0;
  (* src = "word_adder_yosys.v.clean.tainted.final:48" *)
  wire _05__t;
  (* src = "word_adder_yosys.v.clean.tainted.final:56" *)
  wire _06_;
  (* src = "word_adder_yosys.v.clean.tainted.final:57" *)
  wire _06__t;
  (* src = "word_adder_yosys.v.clean.tainted.final:65" *)
  wire _07_;
  (* src = "word_adder_yosys.v.clean.tainted.final:320" *)
  wire _07__j0;
  (* src = "word_adder_yosys.v.clean.tainted.final:66" *)
  wire _07__t;
  (* src = "word_adder_yosys.v.clean.tainted.final:74" *)
  wire _08_;
  (* src = "word_adder_yosys.v.clean.tainted.final:75" *)
  wire _08__t;
  (* src = "word_adder_yosys.v.clean.tainted.final:83" *)
  wire _09_;
  (* src = "word_adder_yosys.v.clean.tainted.final:275" *)
  wire _09__j0;
  (* src = "word_adder_yosys.v.clean.tainted.final:84" *)
  wire _09__t;
  (* src = "word_adder_yosys.v.clean.tainted.final:92" *)
  wire _10_;
  (* src = "word_adder_yosys.v.clean.tainted.final:93" *)
  wire _10__t;
  (* src = "word_adder_yosys.v.clean.tainted.final:101" *)
  wire [31:0] _11_;
  (* src = "word_adder_yosys.v.clean.tainted.final:468" *)
  wire _11__4_0_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:102" *)
  wire _11__t;
  (* src = "word_adder_yosys.v.clean.tainted.final:110" *)
  input clk;
  (* src = "word_adder_yosys.v.clean.tainted.final:111" *)
  reg [4:0] counter;
  (* src = "word_adder_yosys.v.clean.tainted.final:115" *)
  wire [4:0] counter_next;
  (* src = "word_adder_yosys.v.clean.tainted.final:116" *)
  wire counter_next_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:114" *)
  output counter_r;
  reg counter_r;
  (* src = "word_adder_yosys.v.clean.tainted.final:112" *)
  reg counter_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:113" *)
  reg counter_t_flag;
  (* src = "word_adder_yosys.v.clean.tainted.final:124" *)
  input [1:0] func;
  (* src = "word_adder_yosys.v.clean.tainted.final:125" *)
  input func_t;
  reg func_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:126" *)
  input [8:0] inWord;
  (* src = "word_adder_yosys.v.clean.tainted.final:127" *)
  input inWord_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:128" *)
  output [8:0] result;
  (* src = "word_adder_yosys.v.clean.tainted.final:526" *)
  wire result_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:129" *)
  input rstn;
  (* src = "word_adder_yosys.v.clean.tainted.final:379" *)
  wire rstn_c0;
  (* src = "word_adder_yosys.v.clean.tainted.final:382" *)
  wire rstn_j10;
  (* src = "word_adder_yosys.v.clean.tainted.final:130" *)
  input rstn_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:131" *)
  wire running;
  (* src = "word_adder_yosys.v.clean.tainted.final:469" *)
  wire running_c0;
  (* src = "word_adder_yosys.v.clean.tainted.final:472" *)
  wire running_j10;
  (* src = "word_adder_yosys.v.clean.tainted.final:132" *)
  wire running_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:140" *)
  reg [8:0] word;
  (* src = "word_adder_yosys.v.clean.tainted.final:282" *)
  wire word_j0;
  (* src = "word_adder_yosys.v.clean.tainted.final:419" *)
  wire word_j1;
  (* src = "word_adder_yosys.v.clean.tainted.final:144" *)
  wire word_next;
  (* src = "word_adder_yosys.v.clean.tainted.final:145" *)
  wire word_next_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:143" *)
  output word_r;
  reg word_r;
  (* src = "word_adder_yosys.v.clean.tainted.final:153" *)
  reg [8:0] word_sum;
  (* src = "word_adder_yosys.v.clean.tainted.final:498" *)
  wire word_sum_c1;
  (* src = "word_adder_yosys.v.clean.tainted.final:170" *)
  wire word_sum_j0;
  (* src = "word_adder_yosys.v.clean.tainted.final:503" *)
  wire word_sum_j21;
  (* src = "word_adder_yosys.v.clean.tainted.final:157" *)
  wire [8:0] word_sum_next;
  (* src = "word_adder_yosys.v.clean.tainted.final:158" *)
  wire word_sum_next_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:156" *)
  output word_sum_r;
  reg word_sum_r;
  (* src = "word_adder_yosys.v.clean.tainted.final:154" *)
  reg word_sum_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:155" *)
  reg word_sum_t_flag;
  (* src = "word_adder_yosys.v.clean.tainted.final:141" *)
  wire word_t;
  (* src = "word_adder_yosys.v.clean.tainted.final:142" *)
  reg word_t_flag;
  assign _03_ = word_sum + (* src = "word_adder_yosys.v.clean.tainted.final:166" *) _10_;
  assign _05_ = func == (* src = "word_adder_yosys.v.clean.tainted.final:196" *) 1'h1;
  assign _06_ = func == (* src = "word_adder_yosys.v.clean.tainted.final:211" *) 2'h2;
  assign running = counter > (* src = "word_adder_yosys.v.clean.tainted.final:226" *) 1'h0;
  assign _07_ = _05_ && (* src = "word_adder_yosys.v.clean.tainted.final:241" *) inWord;
  assign _08_ = _09_ && (* src = "word_adder_yosys.v.clean.tainted.final:271" *) word;
  assign _09_ = ! (* src = "word_adder_yosys.v.clean.tainted.final:301" *) _05_;
  assign word_next = _07_ || (* src = "word_adder_yosys.v.clean.tainted.final:316" *) _08_;
  assign _21_ = rstn_t | (* src = "word_adder_yosys.v.clean.tainted.final:378" *) counter_next_t;
  assign _22_ = rstn_t | (* src = "word_adder_yosys.v.clean.tainted.final:393" *) word_sum_next_t;
  assign _23_ = rstn_t | (* src = "word_adder_yosys.v.clean.tainted.final:408" *) func_t;
  assign word_sum_t = func_t | (* src = "word_adder_yosys.v.clean.tainted.final:430" *) counter_t;
  assign _24_ = counter_t | (* src = "word_adder_yosys.v.clean.tainted.final:468" *) _11__4_0_t;
  assign _25_ = func_t | (* src = "word_adder_yosys.v.clean.tainted.final:483" *) _04__4_0_t;
  assign _26_ = counter_t | (* src = "word_adder_yosys.v.clean.tainted.final:505" *) word_sum_t;
  always @(posedge clk)
      counter_r <= _12_;
  always @(posedge clk)
      counter_t_flag <= _13_;
  always @(posedge clk)
      counter_t <= _00__t;
  always @(posedge clk)
      counter <= _00_;
  always @(posedge clk)
      word_sum_r <= _15_;
  always @(posedge clk)
      word_sum_t_flag <= _16_;
  always @(posedge clk)
      word_sum_t <= _02__t;
  always @(posedge clk)
      word_sum <= _02_;
  always @(posedge clk)
      word_r <= _14_;
  always @(posedge clk)
      word_t_flag <= _17_;
  always @(posedge clk)
      func_t <= _01__t;
  always @(posedge clk)
      word <= { 8'h00, _01_ };
  assign _10_ = word[$signed(_11_) +: 1];
  assign _11_ = counter - (* src = "word_adder_yosys.v.clean.tainted.final:445" *) 1'h1;
  assign _17_ = word_t_flag ? (* src = "word_adder_yosys.v.clean.tainted.final:351" *) 1'h1 : _01__t;
  assign _18_[0] = word_t_flag ? (* src = "word_adder_yosys.v.clean.tainted.final:353" *) 1'h0 : _01__r;
  assign _14_ = word_r ? (* src = "word_adder_yosys.v.clean.tainted.final:353" *) 1'h1 : _18_[0];
  assign _16_ = word_sum_t_flag ? (* src = "word_adder_yosys.v.clean.tainted.final:359" *) 1'h1 : _02__t;
  assign _19_[0] = word_sum_t_flag ? (* src = "word_adder_yosys.v.clean.tainted.final:361" *) 1'h0 : _02__r;
  assign _15_ = word_sum_r ? (* src = "word_adder_yosys.v.clean.tainted.final:361" *) 1'h1 : _19_[0];
  assign _13_ = counter_t_flag ? (* src = "word_adder_yosys.v.clean.tainted.final:367" *) 1'h1 : _00__t;
  assign _20_[0] = counter_t_flag ? (* src = "word_adder_yosys.v.clean.tainted.final:369" *) 1'h0 : _00__r;
  assign _12_ = counter_r ? (* src = "word_adder_yosys.v.clean.tainted.final:369" *) 1'h1 : _20_[0];
  assign _00_ = rstn ? (* src = "word_adder_yosys.v.clean.tainted.final:370" *) counter_next : 5'h00;
  assign _00__t = rstn ? (* src = "word_adder_yosys.v.clean.tainted.final:378" *) _21_ : rstn_t;
  assign _02_ = rstn ? (* src = "word_adder_yosys.v.clean.tainted.final:385" *) word_sum_next : 9'h000;
  assign _02__t = rstn ? (* src = "word_adder_yosys.v.clean.tainted.final:393" *) _22_ : rstn_t;
  assign _01_ = rstn ? (* src = "word_adder_yosys.v.clean.tainted.final:400" *) word_next : 1'h0;
  assign _01__t = rstn ? (* src = "word_adder_yosys.v.clean.tainted.final:408" *) _23_ : rstn_t;
  assign _04_ = running ? (* src = "word_adder_yosys.v.clean.tainted.final:460" *) _11_[4:0] : 5'h00;
  assign _04__4_0_t = running ? (* src = "word_adder_yosys.v.clean.tainted.final:468" *) _24_ : counter_t;
  assign counter_next = _06_ ? (* src = "word_adder_yosys.v.clean.tainted.final:475" *) 5'h08 : _04_;
  assign counter_next_t = _06_ ? (* src = "word_adder_yosys.v.clean.tainted.final:483" *) func_t : _25_;
  assign word_sum_next = running ? (* src = "word_adder_yosys.v.clean.tainted.final:490" *) _03_ : word_sum;
  assign word_sum_next_t = running ? (* src = "word_adder_yosys.v.clean.tainted.final:505" *) word_sum_t : _26_;
  assign _03__c0 = running;
  assign _03__j10 = counter_t;
  assign _03__t = word_sum_t;
  assign _04__4_0_c0 = _06_;
  assign _04__4_0_j20 = func_t;
  assign _05__j0 = func_t;
  assign _05__t = func_t;
  assign _06__t = func_t;
  assign _07__j0 = func_t;
  assign _07__t = func_t;
  assign _08__t = func_t;
  assign _09__j0 = func_t;
  assign _09__t = func_t;
  assign _10__t = word_sum_t;
  assign _11__t = counter_t;
  assign inWord_t = func_t;
  assign result = word_sum;
  assign result_t = word_sum_t;
  assign rstn_c0 = rstn;
  assign rstn_j10 = rstn_t;
  assign running_c0 = running;
  assign running_j10 = counter_t;
  assign running_t = counter_t;
  assign word_j0 = func_t;
  assign word_j1 = counter_t;
  assign word_next_t = func_t;
  assign word_sum_c1 = running;
  assign word_sum_j0 = word_sum_t;
  assign word_sum_j21 = counter_t;
  assign word_t = func_t;
endmodule
