all:
	g++ trial.cpp -L/usr/bin -lz3 

debug:
	g++ -g trial.cpp -L/usr/bin -lz3

48:
	g++ -g trial.cpp -L/workspace/tools/z3-4.8.8/z3/build -lz3 -I/workspace/tools/z3-4.8.8/z3/src/api/c++ -I/workspace/tools/z3-4.8.8/z3/src/api/

49:
	g++ -g trial.cpp

s:
	g++ -g trial_s.cpp -L/usr/bin -lz3

g:
	g++ -g trial_g.cpp -L/usr/bin -lz3

unsat:
	g++ -g unsat.cpp -L/usr/bin -lz3
