all:
	g++ trial.cpp -L/usr/bin -lz3

debug:
	g++ -g trial.cpp -L/usr/bin -lz3

s:
	g++ -g trial_s.cpp -L/usr/bin -lz3

g:
	g++ -g trial_g.cpp -L/usr/bin -lz3

unsat:
	g++ -g unsat.cpp -L/usr/bin -lz3
