int lui__u0_cpuregs_1_ ( int mem_rdata );
int lui__u0_mem_addr ( int _u0_reg_next_pc );
unsigned char lui__u0_mem_valid (  );
int lui__u0_reg_next_pc ( int _u0_reg_next_pc );
int auipc__u0_cpuregs_1_ ( int _u0_reg_next_pc, int mem_rdata );
int auipc__u0_mem_addr ( int _u0_reg_next_pc );
unsigned char auipc__u0_mem_valid (  );
int auipc__u0_reg_next_pc ( int _u0_reg_next_pc );
int addi__u0_cpuregs_1_ ( int _u0_cpuregs_10_, int _u0_cpuregs_11_, int _u0_cpuregs_12_, int _u0_cpuregs_13_, int _u0_cpuregs_14_, int _u0_cpuregs_15_, int _u0_cpuregs_16_, int _u0_cpuregs_17_, int _u0_cpuregs_18_, int _u0_cpuregs_19_, int _u0_cpuregs_1_, int _u0_cpuregs_20_, int _u0_cpuregs_21_, int _u0_cpuregs_22_, int _u0_cpuregs_23_, int _u0_cpuregs_24_, int _u0_cpuregs_25_, int _u0_cpuregs_26_, int _u0_cpuregs_27_, int _u0_cpuregs_28_, int _u0_cpuregs_29_, int _u0_cpuregs_2_, int _u0_cpuregs_30_, int _u0_cpuregs_31_, int _u0_cpuregs_3_, int _u0_cpuregs_4_, int _u0_cpuregs_5_, int _u0_cpuregs_6_, int _u0_cpuregs_7_, int _u0_cpuregs_8_, int _u0_cpuregs_9_, int _u0_reg_next_pc, int mem_rdata );
int addi__u0_mem_addr ( int _u0_reg_next_pc );
unsigned char addi__u0_mem_valid (  );
int addi__u0_reg_next_pc ( int _u0_reg_next_pc );
