cp 'add_u0.cpuregs[0]_7.ll' ila_sim
cp 'add_u0.cpuregs[1]_7.ll' ila_sim
cp 'add_u0.cpuregs[2]_7.ll' ila_sim
cp 'add_u0.cpuregs[31]_7.ll' ila_sim
cp 'beq_u0.cpuregs[0]_8.ll' ila_sim
cp 'beq_u0.cpuregs[1]_8.ll' ila_sim
cp 'beq_u0.cpuregs[2]_8.ll' ila_sim
cp 'beq_u0.cpuregs[31]_8.ll' ila_sim
cp 'jal_u0.cpuregs[0]_5.ll' ila_sim
cp 'jal_u0.cpuregs[1]_5.ll' ila_sim
cp 'jal_u0.cpuregs[2]_5.ll' ila_sim
cp 'jal_u0.cpuregs[31]_5.ll' ila_sim
cp 'sw_u0.cpuregs[0]_8.ll' ila_sim
cp 'sw_u0.cpuregs[1]_8.ll' ila_sim
cp 'sw_u0.cpuregs[2]_8.ll' ila_sim
cp 'sw_u0.cpuregs[31]_8.ll' ila_sim
