all:
	g++ -I/workspace/research/ILA/autoGenILA/util/verilog-vcd-parser/build -I/workspace/research/ILA/autoGenILA/util/verilog-vcd-parser/src  -l/workspace/research/ILA/autoGenILA/util/verilog-vcd-parser/build/libverilog-vcd-parser.a main.cpp
